### PR TITLE
isDefEq cache for terms not containing metavariables.

### PR DESCRIPTION
**Pull request by leodemoura**

### CODE REVIEW

**Comment by leodemoura** [comment]
!bench

**Comment by leodemoura** [comment]
!bench

**Comment by semorrison** [comment]
Unfortunately the Mathlib test:
```
-- Check that we avoid deep recursion in evaluating large powers.
example : 10^40000000 = 10^40000000 := by norm_num
```
is now taking forever!

**Comment by Kha** [comment]
@semorrison Hmm, this at least seems fine on my machine?
```
$ git describe
port-complete-1153-gf1a26d74c
$ lake +leanprover/lean4-pr-releases:pr-release-2644 env lean -Dtrace.profiler=true <(echo "import Mathlib\nexample : 10^40000000 = 10^40000000 := by norm_num")
[Elab.command] [1.786160s] example : 10 ^ 40000000 = 10 ^ 40000000 := by norm_num
  [Elab.step] [1.177314s] norm_num
    [Elab.step] [1.177298s] norm_num
      [Elab.step] [1.177283s] norm_num
  [Kernel] [0.595197s] typechecking declaration
  ```

**Comment by semorrison** [comment]
Oh, dear! This test has been failing for a while on Apple Silicon (which we don't test in CI). It's not relevant to this PR.

**Comment by Kha** [comment]
!bench

**Comment by semorrison** [comment]
After @Kha's change there are still many regressions in Mathlib: https://github.com/leanprover-community/mathlib4/pull/7606

**Comment by leodemoura** [comment]
!bench

**Review by timotree3 — COMMENTED** [review]
A couple cleanups to comments

**Comment by semorrison** [comment]
I have just merged master, as Mathlib's `nightly-testing` branch has already adapted to other changes on `master`.

**Comment by semorrison** [comment]
@mattrobball just got benchmarking to run on Mathlib for this: an -11% instruction count, and -14% wall clock, which is pretty amazing.

**Comment by semorrison** [comment]
There are nevertheless many places in mathlib where `rw` or `simp` no longer suffices, and we need to use `erw` instead. This is unfortunately consistent with what is being fixed here, but it would be nice if we can finesse both the huge speed up, and fewer `erw` regressions!

Here's a minimised example of a `simp` that now requires an `erw`:

```
set_option autoImplicit true

@[simp] theorem exists_eq_right {p : α → Prop} : (∃ a, p a ∧ a = a') ↔ p a' := sorry

class Preorder (α : Type u) extends LE α, LT α where

class FunLike (F : Sort _) (α : outParam (Sort _)) (β : outParam <| α → Sort _) where
  coe : F → ∀ a : α, β a

instance (priority := 100) hasCoeToFun {F α β} [FunLike F α β] :
    CoeFun F fun _ ↦ ∀ a : α, β a where coe := FunLike.coe

namespace Function

structure Embedding (α : Sort _) (β : Sort _) where
  toFun : α → β

infixr:25 " ↪ " => Embedding

instance {α : Sort u} {β : Sort v} : FunLike (α ↪ β) α fun _ => β where
  coe := Embedding.toFun

namespace Embedding

@[simp] theorem coeFn_mk {α β} (f : α → β) : (@mk _ _ f : α → β) = f := rfl

protected def some {α} : α ↪ Option α := ⟨some⟩

end Embedding

end Function

class Top (α : Type u) where
  top : α

notation "⊤" => Top.top

class OrderTop (α : Type u) [LE α] extends Top α where
  le_top : ∀ a : α, a ≤ ⊤

def WithTop (α : Type _) := Option α

namespace WithTop

instance coeTC : CoeTC α (WithTop α) := ⟨some⟩

instance (priority := 10) le [LE α] : LE (WithTop α) := sorry

theorem some_le_some [LE α] : @LE.le (WithTop α) _ (Option.some a) (Option.some b) ↔ a ≤ b := sorry

instance (priority := 10) lt [LT α] : LT (WithTop α) := sorry

end WithTop

namespace WithTop

instance preorder [Preorder α] : Preorder (WithTop α) where
  le := (· ≤ ·)
  lt := (· < ·)

end WithTop

open Function

structure Finset (α : Type _) where

instance : Membership α (Finset α) := sorry

namespace Finset

def map (f : α ↪ β) (s : Finset α) : Finset β := sorry

theorem mem_map {f : α ↪ β} {s : Finset α} {b : β} : b ∈ s.map f ↔ ∃ a, a ∈ s ∧ f a = b := sorry

end Finset

open Finset

class LocallyFiniteOrder (α : Type _) [Preorder α] where
  finsetIcc : α → α → Finset α
  finset_mem_Icc : ∀ a b x : α, x ∈ finsetIcc a b ↔ a ≤ x ∧ x ≤ b

namespace Finset

variable [Preorder α] [LocallyFiniteOrder α] {a b : α}

def Icc (a b : α) : Finset α := LocallyFiniteOrder.finsetIcc a b

theorem mem_Icc : x ∈ Icc a b ↔ a ≤ x ∧ x ≤ b := LocallyFiniteOrder.finset_mem_Icc a b x

end Finset

namespace WithTop

variable (α) [Preorder α] [OrderTop α] [LocallyFiniteOrder α]

private theorem aux (x : α) (p : α → Prop) :
    (∃ a : α, p a ∧ Option.some a = Option.some x) ↔ p x := by
  simp

instance locallyFiniteOrder : LocallyFiniteOrder (WithTop α) where
  finsetIcc a b :=
    match a, b with
    | (a : α), (b : α) => (Icc a b).map Embedding.some
    | _, _ => sorry
  finset_mem_Icc a b x :=
    match a, b, x with
    | (a : α), (b : α), (x : α) => by
        -- Prior to leanprover/lean4#2644, this was:
        -- simp only [some, Embedding.some, mem_map, mem_Icc, Embedding.coeFn_mk,
        --   some_le_some, aux]
        -- But now `simp` can't use `Embedding.coeFn_mk`, so instead we have to:
        simp only [some, Embedding.some, mem_map, mem_Icc, some_le_some]
        fail_if_success simp only [Embedding.coeFn_mk] -- Used to work, now doesn't
        fail_if_success rw [Embedding.coeFn_mk] -- Used to work, now doesn't
        erw [Embedding.coeFn_mk] -- resort to `erw`
        simp only [aux]
    | _, _, _ => sorry
```

**Comment by semorrison** [comment]
If anyone would like to minimize further, that would be great. I couldn't see what was going on so just went from the top down.

**Comment by eric-wieser** [comment]
That looks like a defeq abuse problem to me; `(Icc a b).map Embedding.some` is of type `Finset (Option α)`, but you're pretending its of type `Finset (WithTop α)`. Does introducing a custom `Embedding.withTopSome` function with the right type make the problem go away?

**Comment by mattrobball** [comment]
`abbrev WithTop := Option` has the same effect

**Review by semorrison — APPROVED** [review]
I think this is good to go, from the point of view of Mathlib.

**Comment by leodemoura** [comment]
> I think this is good to go, from the point of view of Mathlib.

Thanks everybody that invested time on this PR. Awesome teamwork! 
Planning to merge at the end of the day.

**Pull request merged**
