### PR TITLE
Optimizing multiplication and division operations of powers of 2 into shift operations.

### PR DESCRIPTION
**Pull request by hargoniX**

### CODE REVIEW

**Comment by hargoniX** [comment]
I don't see why the Linux CI is failing? It is complaining that a function is missing which is very clearly there.

**Comment by Kha** [comment]
No, `shiftRight` does not exist yet at `Init/Data/Nat/Bitwise.lean:16`. You're trying to optimize the implementation of shifting with itself :) . The optimization should do nothing if the constant is not in the environment yet.

**Comment by Kha** [comment]
Btw, any reason not to leave these optimizations to LLVM? Not sure whether for `Nat` GMP implements the optimization dynamically, but I'd expect so.

**Comment by hargoniX** [comment]
Yeah we can leave this optimization to LLVM as well I guess. In that case do you think the log2 for UInt's is still useful in core? Or should I move it over into std4 instead?

**Comment by Kha** [comment]
In the maintainers meeting we decided there is no real downside to this PR, so happy to merge after it's fixed!

**Pull request merged**
