### PR TITLE
fix: inconsistent use of precompiled symbols from interpreter on Windows

### LINKED ISSUE #1758: Precompilation breakage on Windows
See https://github.com/JLimperg/aesop/issues/28
May or may not have something to do with this line :thinking: 
https://github.com/leanprover/lean4/blob/9fd433785b35a4a309022db05ec6074da64da209/src/library/compiler/ir_interpreter.cpp#L300

### PR DESCRIPTION
**Pull request by Kha**
Fixes #1758

### CODE REVIEW

**Comment by Kha** [comment]
That `lookup_symbol_in_cur_exe` is linear in the number of modules is of course an issue in itself, though I believe this could actually be true for Linux/macOS as well? If we knew which dynlib belonged to which module, we could use the environment to look up a declaration's module and then do a more targeted `dlsym` for that specific dynlib (if any). But let's maybe wait until this function actually turns up in benchmarks.

**Comment by Kha** [comment]
And also Aesop should definitely be precompiled into a single dynlib, which would bring down the number of loaded libs from 135 to 2.

**Comment by JLimperg** [comment]
> And also Aesop should definitely be precompiled into a single dynlib, which would bring down the number of loaded libs from 135 to 2.

Is this something I can do?

**Comment by Kha** [comment]
No, this is a missing Lake feature. I've opened https://github.com/leanprover/lake/issues/136 to track it.

**Comment by JLimperg** [comment]
All right, thanks!

**Pull request merged**
