### PR TITLE
chore: update Lake

### PR DESCRIPTION
**Pull request by tydeu**
Update to ~~v3.1.0~~ **v3.1.1** (hotfix)

### CODE REVIEW

**Comment by Kha** [comment]
Do you want to write up a changelog with the highlights (or a link) for RELEASES.md?

**Comment by tydeu** [comment]
@Kha Sure, I am planning to add a tag for the release on the Lake repository itself with such highlights so either a link to that or the information itself can put in `RELEASES.md`. I just wanted to sanity check the build first in this PR (via CI) before creating the tag.

**Comment by tydeu** [comment]
@Kha Release highlights (and changelog) are now at https://github.com/leanprover/lake/releases/tag/v3.1.0

**Comment by tydeu** [comment]
@Kha Added note to `RELEASE.md` (and bumped to v3.1.1 due to an issue that need quick fixing.

**Pull request merged**
