### PR TITLE
feat: add timing profiling to the new compiler

### PR DESCRIPTION
**Pull request by hargoniX**

### CODE REVIEW

**Comment by Kha** [comment]
I would suggest keeping the trace class as `Compiler` for now, the new output doesn't seem very helpful when enabling specific classes

**Comment by Kha** [comment]
Speaking from a profiling PoV, we should also have a trace node for the entire compiler invocation

**Comment by hargoniX** [comment]
I fixed the first part, for the second we have:
```
@[export lean_lcnf_compile_decls]
def main (declNames : List Name) : CoreM Unit := do
  profileitM Exception "compilation new" (← getOptions) do
    CompilerM.run <| discard <| PassManager.run declNames.toArray
```
right now. What is our policy when the thing already has a `profileitM` call attach? Do I just trace node it anyways? Do I remove profileit?

**Comment by Kha** [comment]
> Do I just trace node it anyways?

Yes, the two profilers are completely separate currently

**Comment by Kha** [comment]
Then I'll merge this as an improvement to profiling that should not otherwise significantly affect compiler dev experience

**Pull request merged**
