### PR TITLE
chore: remove "paper cut" when using `Fin USize.size`

### PR DESCRIPTION
**Pull request by leodemoura**

### CODE REVIEW

**Comment by leodemoura** [comment]
!bench

**Comment by leodemoura** [comment]
@semorrison Could you please help me with this one?

**Comment by semorrison** [comment]
Okay, hopefully Mathlib is happy with this one now.

**Comment by semorrison** [comment]
Mathlib CI integration is just a mess at the moment due to the number of breaking changes we have in the air at the same time.

Since this one has previously succeeded with Mathlib, but doesn't now, I think we should declare success, and I'll sort out the details once it is actually in the nightly.

**Pull request merged**
