### PR TITLE
chore: CI: mark "Build matrix complete" as cancelled if builds cancelled

### PR DESCRIPTION
**Pull request by Kha**

### CODE REVIEW

**Comment by Kha** [comment]
I'm always confused when it's marked as actually failed

**Comment by Kha** [comment]
Not that GitHub's icons care!
image

**Comment by nomeata** [comment]
If it works, then great of course! But does it?

**Comment by Kha** [comment]
> Not that GitHub's icons care! image

(https://github.com/orgs/community/discussions/8336)

**Review by nomeata — APPROVED** [review]
Ah, misunderstood your first comment. All well then!

**Pull request merged**
