### PR TITLE
chore: stage0 autoupdater action

### PR DESCRIPTION
**Pull request by nomeata**
This Github action automatically updates `stage0` on `master` if
`src/stdlib_flags.h` and `stage0/src/stdlib_flags.h`
are out of sync there.

It bypasses the merge queue to be quick, this way, an out-of-date stage0 on on
master should only exist for a few minutes.

Needs access to a _deploy SSH key_ with write permission.

### CODE REVIEW

**Comment by Kha** [comment]
@nomeata Deploy key deployed. Can we get a `workflow_dispatch` as well in order to trigger updates manually?

**Review by Kha — APPROVED** [review]

**Comment by nomeata** [comment]
> @nomeata Deploy key deployed. Can we get a `workflow_dispatch` as well in order to trigger updates manually?

Yes, should be relatively straight-forward. Separate PR, I guess.

Would you want it to update even if `stdflags.h` are the same, or still do the same check?

**Comment by Kha** [comment]
> Would you want it to update even if `stdflags.h` are the same, or still do the same check?

No check, we want to do this to e.g. make new LS features available in stage0.

**Comment by nomeata** [comment]
> > @nomeata Deploy key deployed. Can we get a `workflow_dispatch` as well in order to trigger updates manually?
> 
> Yes, should be relatively straight-forward. Separate PR, I guess.

https://github.com/leanprover/lean4/pull/3052

**Pull request merged**
