### PR TITLE
fix highlight of `deriving instance`

### PR DESCRIPTION
**Pull request by lovettchris**
with this fix:

image

without this fix the `deriving instance` bleeds all the way to the closing `where`.

image

### CODE REVIEW

**Comment by Kha** [comment]
Unclean history again

**Comment by lovettchris** [comment]
are you talking about the 4 commits?  doesn't squash merge take care of squashing the 4 commits you see there?

**Comment by Kha** [comment]
Oh I see, the conflict message is specific to rebase... I wasn't aware of that because most other contributors rebase their branches

**Comment by Kha** [comment]
And because of that I now merged it using the wrong commit message...

**Comment by leodemoura** [comment]
I will make a destructive update.

**Pull request merged**
