### PR TITLE
Fix duplicate in fakeDepRoot

### PR DESCRIPTION
**Pull request by Anderssorby**
This fixes an issue with diamond dependencies in nix fakeDepRoot.

### CODE REVIEW

**Comment by Kha** [comment]
So you do have two different versions of the same module? As I said on Zulip, that will be problematic no matter what. You really should avoid it.

**Comment by Anderssorby** [comment]
This is a different, but similar issue. It fixes that different dependencies may depend on the same dependency.

**Comment by Kha** [comment]
If it is literally the same dependency, I don't think this should happen. `allExternalDeps` itself is already `lib.unique`'d.

**Comment by Anderssorby** [comment]
Yes, but for some reason it complains that `Init` and `Lean` already exists.

**Comment by Kha** [comment]
Then you'll need to take a closer look at what's up with your `allExternalDeps`.
```
nix-repl> lib.unique [ hello hello ]
[ «derivation /nix/store/8dr2lhv3kriyw8qhg66dszr0vl3grxya-hello-2.10.drv» ]
```

**Comment by Anderssorby** [comment]
@Kha It is caused by compiling with different lean versions. This should not happen however since each flake dependency's lean input follows the lean of it's parent.

**Comment by Anderssorby** [comment]
I'm closing this since this is not the right solution to the problem.

**Pull request closed without merging**
