### PR TITLE
Generate LLVM module of runtime for use in the LLVM backend

### PR DESCRIPTION
**Pull request by Kha**
...hackily by replicating the standard compilation in an `add_custom_command`

### CODE REVIEW

**Comment by Kha** [comment]
@DanielFabian If the build works for you as well and the generated file (`stage1/runtime/libleanruntime.bc`) looks good to you, I think we can merge this one!

**Comment by DanielFabian** [comment]
I'll look at it tonight. Apart from that, let's please run a !bench just to be safe.

**Comment by DanielFabian** [comment]
!bench

**Comment by Kha** [comment]
The executable is unaffected (until you include the bitcode file into it), it's a separate target. There's a bit of compilation overhead until ccache is full because we compile the runtime twice now, but we don't have benchmarks for the whole, uncached build because it takes too long. Oh, and we do not bench with `LLVM=ON` yet.

**Comment by DanielFabian** [comment]
where will the file sit in the nix build?

**Comment by Kha** [comment]
It should become a part of `leancpp`, like `shell/lean.cpp.o`. I've left turning on LLVM integration for Nix to #531, will update it accordingly then.

**Comment by DanielFabian** [comment]
It looks almost like this is not a good merge. Here's what I'm getting and I double-checked and I'm fairly confident that I cherry-picked your stuff correctly. At least the only change between our respective `CMakeList.txt` files is a single file that I added.

```shell-session
❯ make -j16
[  6%] Performing build step for 'stage0'
[  0%] Built target initialize
[  0%] Built target shell
[ 12%] Built target Std
[ 14%] Built target runtime
[ 15%] Built target leanruntime
[ 15%] Built target util
[ 30%] Built target Init
[ 31%] Built target constructions
[ 34%] Built target kernel
[ 38%] Built target library
[ 43%] Built target compiler
[ 46%] Built target leancpp
[ 99%] Built target Lean
[100%] Built target lean
[ 12%] No install step for 'stage0'
[ 18%] Completed 'stage0'
[ 50%] Built target stage0
[ 56%] Performing configure step for 'stage1'
-- No build type selected, default to Release
-- 64-bit machine detected
-- Using compressed object headers and only 32-bits for reference counter, this feature assume the OS only uses memory addresses < 2^48
-- Found CLANG
-- Using ClangConfig.cmake in:
-- Found LLVM 11.0.0
-- Using LLVMConfig.cmake in: /usr/lib/llvm-11/cmake
-- git commit sha1: 9516da61f0518d2e6a0ba075ba6db6e5c0f6611e
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dany/src/lean4/build/stage1
[ 62%] Performing build step for 'stage1'
make[5]: *** No rule to make target '/home/dany/src/lean4/src/runtime/lean_inlines.c', needed by 'runtime/libleanruntime.bc'.  Stop.
make[4]: *** [CMakeFiles/Makefile2:1262: runtime/CMakeFiles/runtime_bc.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[  1%] Built target initialize
[ 18%] Built target leanruntime
[ 19%] Built target shell
[ 28%] Built target constructions
[ 40%] Built target runtime
[ 58%] Built target util
[ 65%] Built target kernel
[ 80%] Built target library
[ 99%] Built target compiler
make[3]: *** [Makefile:163: all] Error 2
make[2]: *** [CMakeFiles/stage1.dir/build.make:113: stage1-prefix/src/stage1-stamp/stage1-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:218: CMakeFiles/stage1.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by Kha** [comment]
Added the missing file. That's what I get for not building with Nix for once!

**Comment by DanielFabian** [comment]
sorry, but this doesn't work either. The files like alloc.cpp.ll don't look like LLVM at all, but more like assembly:
```assembly
        .file   "alloc.cpp"
        .text
        .section        .rodata
        .type   _ZStL19piecewise_construct, @object
        .size   _ZStL19piecewise_construct, 1
_ZStL19piecewise_construct:
        .zero   1
        .section        .text._ZnwmPv,"axG",@progbits,_ZnwmPv,comdat
        .weak   _ZnwmPv
        .type   _ZnwmPv, @function
_ZnwmPv:
.LFB364:
        .cfi_startproc
        endbr64
        pushq   %rbp
        .cfi_def_cfa_offset 16
        .cfi_offset 6, -16
        movq    %rsp, %rbp
        .cfi_def_cfa_register 6
        movq    %rdi, -8(%rbp)
        movq    %rsi, -16(%rbp)
        movq    -16(%rbp), %rax
        popq    %rbp
        .cfi_def_cfa 7, 8
        ret
        .cfi_endproc
.LFE364:
        .size   _ZnwmPv, .-_ZnwmPv
        .section        .text._ZdlPvS_,"axG",@progbits,_ZdlPvS_,comdat
        .weak   _ZdlPvS_
        .type   _ZdlPvS_, @function
_ZdlPvS_:
.LFB366:
        .cfi_startproc
        endbr64
        pushq   %rbp
        .cfi_def_cfa_offset 16
        .cfi_offset 6, -16
        movq    %rsp, %rbp
        .cfi_def_cfa_register 6
        movq    %rdi, -8(%rbp)
```

**Comment by Kha** [comment]
I'm afraid I can't reproduce that, using LLVM 10
```bash
$ head runtime/runtmp/alloc.cpp.ll
; ModuleID = '/home/sebastian/lean/lean/src/runtime/alloc.cpp'
source_filename = "/home/sebastian/lean/lean/src/runtime/alloc.cpp"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%"class.std::ios_base::Init" = type { i8 }
%"struct.lean::allocator::page" = type { %"struct.lean::allocator::page_header", [8136 x i8] }
%"struct.lean::allocator::page_header" = type <{ %"class.lean::atomic", %"struct.lean::allocator::page"*, %"struct.lean::allocator::page"*, i8*, i32, i32, i32, i32, i8, [7 x i8] }>
%"class.lean::atomic" = type { %"struct.lean::allocator::heap"* }
%"struct.lean::allocator::heap" = type { %"struct.lean::allocator::segment"*, %"struct.lean::allocator::heap"*, [512 x %"struct.lean::allocator::page"*], [512 x %"struct.lean::allocator::page"*], i8*, i32, %"class.lean::mutex", i8*, i64 }
file runtime/libleanruntime.bc
runtime/libleanruntime.bc: LLVM IR bitcode
```

**Comment by DanielFabian** [comment]
sorry, it was me being dumb, I didn't notice, that CMake used GCC instead of clang... it's compiling now.

**Comment by Kha** [comment]
No I wonder what GCC made of `-emit-llvm` :smile:

**Comment by DanielFabian** [comment]
yep ;-). I think it just ignored it, and used `-S`, i.e. compile to assembly instead. FYI, it's fine, I got a libleanruntime.bc and all is well ;-)

**Comment by DanielFabian** [comment]
and llvm-dis works just fine now ;-)

**Pull request merged**
