### PR TITLE
fix: update System.FilePath.parent to handle edge cases for absolute paths

### LINKED ISSUE #3618: `System.FilePath.parent` bug at root
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

```lean
#eval (System.FilePath.mk "/home").parent
```
results in `some (FilePath.mk "")`, which isn't a valid path, rather than `some (FilePath.mk "/")` as expected.

### Versions

Lean: "4.6.0"

OS:
```
⮞ uname -a
Linux dorian 6.6.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 20 Nov 2023 23:18:21 +0000 x86_64 GNU/Linux

⮞ lsb_release -a
LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```
### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

### PR DESCRIPTION
**Pull request by austinletson**
System.FilePath.parent did not return the correct parent path in the case of absolute file paths 

Example of previous behavior
```
(FilePath.mk "/foo").parent -> some (FilePath.mk "")

(System.FilePath.mk "/").parent -> some (FilePath.mk "")
```

The new behavior is based on rust's std::path::Path::parent function (as previously described in comment in System.FilePath)

Example of updated behavior
```
(System.FilePath.mk "/foo").parent -> some (FilePath.mk "/")

(System.FilePath.mk "/").parent -> none
```

Behavior for relative file paths is unchanged

Closes #3618

### CODE REVIEW

**Comment by austinletson** [comment]
I created this PR as draft since the relevant issue #3618 has not been approved by a maintainer

**Comment by austinletson** [comment]
awaiting-review

**Comment by semorrison** [comment]
@austinletson, would you mind rebasing onto `master` (`nightly-with-mathlib` is fine too)? We can get this merged.

**Comment by semorrison** [comment]
@austinletson, there is a test failure on Windows. Could you take a look?

**Comment by austinletson** [comment]
@semorrison I fixed the failing tests on Windows and added additional tests specifically for Windows for completeness. 

All CI looks to be passing now. Let me know if there is anything else needed to add this to the merge queue

**Pull request merged**
