### PR TITLE
test: C trigraph

### PR DESCRIPTION
**Pull request by nomeata**
add a test file that checks that C trigraphs in string literals are not
miscompiled.

### CODE REVIEW

**Comment by digama0** [comment]
is there a way to set this test up to also ensure you don't get the warning from #2829?

**Comment by nomeata** [comment]
Yeah, that would be good. This use case (check stderr/out of `leanc`) doesn't seem to be supported by the test suite at the moment, or I didn’t see it.

A simple hammer would be to make tests in `lean/compiler` fail whenever they have output, but that would break existing files:
```
1549: Test command: /nix/store/m6xrxfbgvm8791x09f7ims712hwy3aqh-bash-interactive-5.2-p15/bin/bash "-c" "PATH=/home/jojo/build/lean/lean4/build/release/stage1/bin:$PATH LEAN_CC=/nix/store/xkj1aa2f8gmqs1q3vqxcnl89n1iqwakv-clang-wrapper-15.0.7/bin/clang CXX='/nix/store/xkj1aa2f8gmqs1q3vqxcnl89n1iqwakv-clang-wrapper-15.0.7/bin/clang++  -O3 -DNDEBUG' LEANC_OPTS=' -O3 -DNDEBUG' ./test_single.sh append.lean"
1549: Working Directory: /home/jojo/build/lean/lean4/src/../tests/compiler
1549: Test timeout computed to be: 1500
1549: running C program...
1549: append.lean:3:10: warning: unused variable `xs` [linter.unusedVariables]
 4/53 Test #1549: leancomptest_append.lean .....................   Passed    0.33 sec
test 1550
      Start 1550: leancomptest_array.lean
```

The next level of sophistication is to have `.expect.out` files for both `lean` and `leanc` in `tests/compiler` tests. That would require a lot of empty files.

The next next level of sophistication is to treat a missing `.expect.out` as an empty file. That’s what I did when setting up the Motoko compiler test suite, and found it quite convenient and effective.

**Comment by digama0** [comment]
> The next next level of sophistication is to treat a missing .expect.out as an empty file. That’s what I did when setting up the Motoko compiler test suite, and found it quite convenient and effective. Woulds also require changes to diff_produced.

I was going to suggest treating a missing `.expect.out` as a run test, i.e. you just ignore the output unless you are told to compare it to something.

**Comment by nomeata** [comment]
Also a viable option. I like “assert output is empty” is a good implicit default (also because it means that many tests only need the `.lean` file and nothings else) and “ignore output” something that should be explicit. In general, test suite organization is very prone to developer bikeshedding :-)

**Comment by digama0** [comment]
If all existing tests have no output, then that's fine, but my guess is that the status quo is that the output is ignored so checking / asserting all the tests will mean lots of new files.

**Comment by Kha** [comment]
Not checking the warning seems good enough for now

**Pull request merged**
