### PR TITLE
fix: upgrade instance synth order issues to hard errors

### PR DESCRIPTION
**Pull request by kmill**
Motivated [by a user's question](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Confusing.20instance.20error/near/471539940), this increases the severity of the "cannot find synthesization order" message from a log error to throwing an exception. This saves some confusion about whether the instance was added or not.

### CODE REVIEW

**Review by TomasPuverle — COMMENTED** [review]
My two cents: As the originator of this question/issue, the new wording is more helpful and would have alleviated some of the confusion I expressed on Zulip.
Many thanks!

**Comment by Kha** [comment]
> This isn't a hard error

Just checking, do you think this was intentional and should stay that way?

**Comment by Kha** [comment]
Triage team agrees: making this a hard error seems like the safer option

**Comment by TomasPuverle** [comment]
> Just checking, do you think this was intentional and should stay that way?

I am not sure if this question was aimed at me or @kmill.  I don't have a preference - ultimately, I was just confused when I saw "error: ..." but the code still ran.

**Comment by kmill** [comment]
@Kha Should we leave the `synthInstance.checkSynthOrder` option? My thoughts are
* if we have the option, then since the check can be turned off, it's clearly safe to proceed, so we should log a warning like in this PR; but
* if we want it to be a hard error due to safety, then we shouldn't be able to proceed without the check.

**Comment by digama0** [comment]
I mostly agree with you, but this is not the only error that can be turned off. `set_option hygiene` is another one that comes to mind.

**Pull request merged**
