### PR TITLE
fix: hovers on binders with metavariables

### LINKED ISSUE #4078: Rpc Error when hovering variable
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

In the following code:
```lean
import Lean.Data.HashMap

open Lean

inductive Decl (α : Type) where
  | atom (idx : α)
  deriving BEq, Hashable

def Cache (α : Type) := Unit

structure CacheHit (decl : Decl α) where
  idx : Nat

def Cache.find (cache : Cache α) (decl : Decl α) : (CacheHit decl) :=
  sorry

theorem denote_mkAtom_cached {cache : Cache α} {hit} (h : cache.find (.atom v) = hit) :
    hit = hit := by
  sorry
```
Hovering `hit` at `{hit}` yields 
```
Error updating: Error fetching goals: Rpc error: InternalError: unknown metavariable '?_uniq.927'. Try again.
```
In the infoview. Furthermore the hover itself prints:
```
hit : failed to pretty print expression (use 'set_option pp.rawOnError true' for raw representation)
```
However hovering on `hit` in the theorem statement `hit = hit` does reveal a proper hover.

### Steps to Reproduce

1. Copy code into editor
2. Hover over `{hit}`
3. :boom: 

**Expected behavior:** The hover should be the same at the binder and the equation

**Actual behavior:** A broken hover and seemingly something wrong with the LSP as well.

### Versions
4.8.0-rc1

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

### PR DESCRIPTION
**Pull request by nomeata**
this fixes #4078. It is an alternative fix to the one in #4137, suggested
by @kmill.

Incidentially, it makes the unused variable linter better. My theory is that
if we don’t reset the info when backtracking, the binder shows up more than
once in the info tree, and then it is considered “used”, although there are
just multiple binders.

### CODE REVIEW

**Comment by nomeata** [comment]
The changes to the test output looks reasonable, in one case we see that the info tree no longer contains entries from a back-tracked attempt at elaboration.

**Comment by nomeata** [comment]
Interesting, this makes the unused-variable-linter better (see https://github.com/leanprover-community/batteries/pull/802

**Review by kmill — APPROVED** [review]
This looks good to me (auto implicits should act as if they were always there, right?), though it'd be good to get another opinion since I'm not completely sure why `restore` doesn't restore info trees to begin with.

**Comment by Kha** [comment]
> I'm not completely sure why `restore` doesn't restore info trees to begin with.

I don't know. It might be good to double-check and document the need for this parameter but that shouldn't hold back this PR.

**Review by Kha — APPROVED** [review]

**Comment by Kha** [comment]
IIRC the original intent was to retain information from overloading but it seems some of that was switched to `restoreInfo := true`

**Pull request merged**
