### PR TITLE
fix: pass usedSimps argument

### PR DESCRIPTION
**Pull request by kim-em**

### CODE REVIEW

**Review by digama0 — APPROVED** [review]

**Comment by semorrison** [comment]
It's slightly awkward to write a test for this: `simp?` is in `Std`, which is how this should really be tested. I can add a test that uses the plumbing functions if desired.

**Comment by digama0** [comment]
There is an alternate syntax for `simp?` which is to set `set_option tactic.simp.trace true`. I think there is a test file for this?

**Comment by semorrison** [comment]
> tactic.simp.trace

I've added a test to `tests/lean/simp_trace.lean`.

**Comment by leodemoura** [comment]
CI is not green.

**Pull request closed without merging**
