### PR TITLE
chore: bundle libatomic in releases

### PR DESCRIPTION
**Pull request by gebner**
This should make `lean +gebner/lean4:bundlelibatomic` work again (once CI finishes after lunch).

### CODE REVIEW

**Comment by Kha** [comment]
LGTM modulo first commit

**Comment by gebner** [comment]
> modulo first commit

This is a CI feature that I've wanted for a long time, I'm really tired of naming all tags like `vrpcrace` etc.

**Comment by gebner** [comment]
Okay, I've validated the fix.  The downloaded binaries now work on both NixOS and Ubuntu.

**Comment by gebner** [comment]
Ah I see.  It's unfortunate that uploading binaries is tied to appearing on the releases tab. :disappointed:  Setting it as prerelease or draft doesn't help either.

Note that we can always remove a release manually if we don't want it to show up in the list (but then you can't use elan on it either :sad:).

> We don't want https://github.com/leanprover/lean4/releases/tag/NFM2022 etc. to appear as a release

We probably don't want it to show up in the list, but still available via elan.

**Comment by Kha** [comment]
> We probably don't want it to show up in the list, but still available via elan.

So far we only really used them in links to code, in the actual supplements we use regular nightly releases as all those tags are on `master`.

**Pull request merged**
