### PR TITLE
feat: multiple `delta`

### PR DESCRIPTION
**Pull request by digama0**
This is used by mathport. `delta foo, bar` is like `delta foo` but it simultaneously unfolds any of the declarations in the list in the chosen targets.

### CODE REVIEW

**Comment by Kha** [comment]
Do we have a top-level comma-separate list anywhere else in the tactic syntax? Why not space-separated?

**Review by Kha — CHANGES_REQUESTED** [review]
You should also update the docstrings

**Comment by digama0** [comment]
I added docstrings and used space-separated lists for `unfold` / `delta` tactic and conv.

**Comment by Kha** [comment]
> It's also used in `unfold`. We could go back to space separated though.

Oh wow, that *is* unexpected. Don't we need `colGt` now though?
@leodemoura Do you agree that we should usually separate identifiers by spaces in tactics?

**Comment by digama0** [comment]
oops yes, it needs `colGt`

**Comment by leodemoura** [comment]
> @leodemoura Do you agree that we should usually separate identifiers by spaces in tactics?

Yes, we have been using this convention in other tactics.
Happy to talk about whether we should change this convention in the next dev meeting.

**Pull request merged**
