### PR TITLE
feat: improve import duplicate definition error

### PR DESCRIPTION
**Pull request by gebner**

### CODE REVIEW

**Comment by gebner** [comment]
Not sure how to test this, I couldn't find any way to import local files in the tests.

**Comment by leodemoura** [comment]
It is not very convenient to add this kind of test. We usually create a small package here
https://github.com/leanprover/lean4/tree/master/tests/pkg

**Comment by gebner** [comment]
Right, I've seen those tests.  But there you can't easily test the error message.  (All it checks is that it builds, which it of course won't.)

**Comment by leodemoura** [comment]
Some of them test for errors. It is not nice. 
https://github.com/leanprover/lean4/blob/master/tests/pkg/prv/test.sh

**Comment by gebner** [comment]
Ugh, that's both ugly and a lot of effort.  If you want, I can add such a test for the error message here, but I'd rather avoid it.

**Pull request merged**
