### PR TITLE
chore: rename Array.flatten to join, and upstream lemmas

### PR DESCRIPTION
**Pull request by kim-em**

### CODE REVIEW

**Comment by david-christiansen** [comment]
What is the motivation for this? It's a closer match to Haskell, but I think most programmers would have an easy time guessing "flatten" and a difficult time guessing "join" for this operation.

**Comment by digama0** [comment]
I second David's concern, `flatten` is a more intuitive name while `join` is a monad-brained name. (I think I've said similar things about `List.bind` vs `flatMap` in the past, which IMO is even worse.)

**Comment by kim-em** [comment]
If everyone is happy with renaming `List.join` also to `List.flatten`, then I am perfectly happy to go the other way.

**Comment by kim-em** [comment]
Replaced by #5551

**Pull request closed without merging**
