### PR TITLE
fix: potential buffer overrun

### PR DESCRIPTION
**Pull request by lovettchris**
clang-cl compiler on Windows reports this error:

D:\Temp\lean_windows\util\shell.cpp(243,6): error C2440: 'initializing': cannot convert from 'const char [13]' to 'const char' 

because this command line option is the full 12 chars reserved in `struct option` which leaves no room for the null terminator.

```
    {"print-prefix", no_argument,       &print_prefix, 1},
```

### CODE REVIEW

**Comment by leodemoura** [comment]
Could you please `squash`? For some reason, the GitHub "Squash and merge" is not available for this PR.

**Comment by lovettchris** [comment]
Does this help?
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Comment by Kha** [comment]
Still doesn't work. Could you please reduce the PR to a single commit without merge commits?

**Comment by lovettchris** [comment]
ok, I'm creating a new fork and pull request, see https://github.com/leanprover/lean4/pull/839

**Pull request closed without merging**
