### PR TITLE
perf: short-circuit all antiquotation parsers

### PR DESCRIPTION
**Pull request by Kha**
Another ~13% speedup on my machine (after update-stage0 for the `parser!` change)
perf diff:
```
     3.87%     -2.77%  parser.lean.out     [.] lean_apply_2
     1.03%     -1.01%  parser.lean.out     [.] l_Lean_Parser_dollarSymbol___elambda__1
    13.83%     +1.00%  parser.lean.out     [.] lean_alloc_small
     4.47%     +0.89%  parser.lean.out     [.] l_RBNode_find___main___at___private_Init_Lean_Data_Trie_5__matchPrefixAux___main___spec__1___rarg
    13.59%     +0.88%  parser.lean.out     [.] lean_del
     1.35%     -0.85%  parser.lean.out     [.] l_Lean_Parser_mergeOrElseErrors
     2.45%     -0.77%  parser.lean.out     [.] l_Lean_Parser_tokenFn
     3.06%     +0.54%  parser.lean.out     [.] l_Lean_Syntax_mreplace___main___at_Lean_Syntax_updateLeading___spec__1
     2.20%     +0.51%  parser.lean.out     [.] l___private_Init_Lean_Data_Trie_5__matchPrefixAux___main___rarg
```

### CODE REVIEW

**Comment by Kha** [comment]
Ah, the diff doesn't look very impressive because functions that do not occur in capture in *any* snapshots in the newer executable are listed at the bottom
```
     1.33%             parser.lean.out     [.] l_Lean_Parser_setExpectedFn___rarg
     0.67%             parser.lean.out     [.] l_Lean_Parser_tryFn
     0.34%             parser.lean.out     [.] l_Lean_Parser_mkAntiquot___elambda__2
     0.30%             parser.lean.out     [.] l___private_Init_Lean_Parser_Parser_16__isDollar
```

**Comment by leodemoura** [comment]
Nice!

**Comment by Kha** [comment]
Speedcenter says -13% on Core.lean but +38% on compilation :scream: http://speedcenter.informatik.kit.edu/lean/changes/?tre=10&rev=933ff6dc88795cf9df9bd8bf49545919b4219053&exe=37&env=2

**Comment by leodemoura** [comment]
The problem is the code explosion produced by `withAntiquot`. We got 100k new lines of code.
I rewrote it as:
```lean
def tryAnti (c : ParserContext) (s : ParserState) : Bool :=
let (s, stx?) := peekToken c s;
match stx? with
| some stx@(Syntax.atom _ sym) => sym == "$"
| _                            => false

@[inline] def withAntiquotFn (antiquotP p : ParserFn) : ParserFn :=
fun c s => if tryAnti c s then orelseFn antiquotP p c s else p c s
```

**Comment by leodemoura** [comment]
I think it fixes the code overhead and preserves the perf improvement.

**Comment by Kha** [comment]
Results are in! http://speedcenter.informatik.kit.edu/lean/changes/?tre=10&rev=7e959f83933fd2a88f8aceb9546860b12830d316&exe=37&env=2
=> reduced to 7% compilation overhead, nice

**Comment by Kha** [comment]
There probably is just a handful of `parser!`s where this actually matters and for all others it's just compilation overhead, but finding those...

**Pull request closed without merging**
