### PR TITLE
doc: enable syntax highlighting for the Macro Overview

### PR DESCRIPTION
**Pull request by eyelash**

### CODE REVIEW

**Comment by leodemoura** [comment]
@eyelash Thanks for the PR.
The CI failed to compile the manual. I did not investigate the issue. Could you please take a look?

**Comment by eyelash** [comment]
@leodemoura I fixed the CI. There was, however, an example that did not compile and I haven't figured out yet how to fix it:

```lean
syntax (name := myExfalsoParser) "myExfalso" : tactic

@[macro myExfalsoParser] def implMyExfalso : Lean.Macro :=
  fun stx => Lean.mkNode `Lean.Parser.Tactic.apply
    #[Lean.mkAtomFrom stx "apply", Lean.mkCIdentFrom stx ``False.elim]

example (p : Prop) (h : p) (f : p -> False) : 3 = 2 := by
  myExfalso
  exact f h
```

with the following error message:

```
example.lean:4:13: error: type mismatch
  Lean.mkNode `Lean.Parser.Tactic.apply #[Lean.mkAtomFrom stx "apply", (Lean.mkCIdentFrom stx `False.elim).raw]
has type
  Lean.TSyntax `Lean.Parser.Tactic.apply : Type
but is expected to have type
  Lean.MacroM Lean.Syntax : Type
example.lean:8:2: error: tactic 'myExfalsoParser' has not been implemented
```

Maybe the community can help with this one. But even without syntax highlighting for this example, this PR should be an improvement over the current state.

**Comment by eyelash** [comment]
Adding `pure` makes the example compile:

```lean
@[macro myExfalsoParser] def implMyExfalso : Lean.Macro :=
  fun stx => pure (Lean.mkNode `Lean.Parser.Tactic.apply
    #[Lean.mkAtomFrom stx "apply", Lean.mkCIdentFrom stx ``False.elim])
```

If someone can confirm that this is the correct fix, I will gladly open a pull request to enable syntax highlighting for this example as well.

**Comment by gebner** [comment]
Yes, this is just missing the `pure`.  A long time ago we used to have a coercion from `α` to `m α` (and so the `pure` wasn't required), but we've removed it since then.

**Pull request merged**
