### PR TITLE
feat: cache built file hashes

### PR DESCRIPTION
**Pull request by tydeu**
After building a file, Lake saves the file's hash to a `.hash` which can be reused by future builds to avoid the performance cost of rehashing the file.

A new CLI option `--rehash`/`-H` can be used to prevent Lake from using `.hash` files.

### CODE REVIEW

**Comment by Vtec234** [comment]
Is the performance cost of hashing source code a significant fraction of build times / Lake overhead? I would find that quite surprising!

**Comment by tydeu** [comment]
@Vtec234 This does not in fact cache source hashes, just build outputs (e.g., `.olean`, `.c`, `.o`, `.so`, etc.).

**Comment by Kha** [comment]
Any measurements of the impact? :)

**Comment by digama0** [comment]
@Vtec234 Yes, this was a major factor in reducing the runtime of lean-cache, see https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Lake.20server.20uses.20options.20from.20the.20wrong.20package/near/376858786

**Comment by tydeu** [comment]
!bench

**Comment by tydeu** [comment]
Comparing this run on this PR with the run with the base master commit + benchmark (i.e., https://github.com/leanprover/lean4/pull/2457#issuecomment-1699782763) gives the [expected significant improvement](http://speed.lean-fro.org/lean4/compare/275405ae-de4b-4046-9bd6-9968c8a7b6f3/to/bab50d33-13a1-40c4-85a0-fda5f93f8b22?hash2=b56cb22b1e3bacfe9a47682997102840c61347fc) in no-op build performance. From the comparison:

```diff
  Benchmark         Metric         Change
  =================================================
+ lake build no-op  branches       -32.7% (-63 σ)
+ lake build no-op  instructions   -44.5% (-96.2 σ)
+ lake build no-op  maxrss         -54.8% (-48.3 σ)
+ lake build no-op  task-clock     -57.6% (-25.1 σ)
```

**Comment by tydeu** [comment]
!bench

**Comment by tydeu** [comment]
Comparing [the two runs](http://speed.lean-fro.org/lean4/compare/7ef02c1c-37bd-4a78-b8fb-bc3ab93f4670/to/bab50d33-13a1-40c4-85a0-fda5f93f8b22?hash2=143e265d24ce3ce0ad543e6dbb18683b533eaeb3) with a split between the Lean and dummy no-op builds, only the Lean build displays a significant improvement. Thus, this the change is clearly dependent on the complexity of the OLean code.

**Pull request merged**
