### PR TITLE
Auto-complete declaration names in arbitrary namespaces

### PR DESCRIPTION
**Pull request by Kha**
This fixes exactly #1659. It does not (yet) attempt to do fuzzy-matching across the entire declaration name including namespaces, as that is potentially slow and can yield unhelpful results if the namespace is the *only* thing that matched; on the other hand, some examples in https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/autocomplete.20woes are of this kind, so this is something we should revisit in the future.

### CODE REVIEW

**Comment by eric-wieser** [comment]
> It does not (yet) attempt to do fuzzy-matching across the entire declaration name including namespaces,

One thing that's quite common is to not know whether the lemma you're looking for is of the form `SomeProp.someLemma` or `someProp_someLemma` (`_` vs `.` and `s` vs `S`). Is this something that autocomplete can help with as of this PR?

**Comment by Kha** [comment]
> Is this something that autocomplete can help with as of this PR?

Only if matching against `someLemma` is sufficient for finding it

**Comment by leodemoura** [comment]
We need more autocompletion tests at `tests/lean/interactive`.

**Comment by Kha** [comment]
> > It does not (yet) attempt to do fuzzy-matching across the entire declaration name including namespaces,
> 
> One thing that's quite common is to not know whether the lemma you're looking for is of the form `SomeProp.someLemma` or `someProp_someLemma` (`_` vs `.` and `s` vs `S`). Is this something that autocomplete can help with as of this PR?

I'm wondering whether including the last *two* segments, i.e. usually the type/prop and function/theorem would yield a sensible balance of exhaustiveness, relevance, and performance. But that feels a bit arbitrary, let's go with this more limited and clear-cut extension for now.

**Comment by Kha** [comment]
I think this is ready to go as a relatively conservative extension of the current behavior, unless someone can think of additional interesting tests to add

**Pull request merged**
