### PR TITLE
fix: `variable` must execute pending tactics and elaboration problems

### LINKED ISSUE #2226: `def` fails without error (`by` in `variable`)
In this (definitely contrived) example, the `foo` declaration fails, as evidenced by the fact that it is not in the environment, but no error is reported:
```lean
variable (A : Nat) (B : by skip)
def foo := A = B -- no error is reported

#print foo -- unknown constant 'foo'
```
Using `def foo : Prop` instead causes the declaration to succeed and report that it uses `sorry`.

### LINKED ISSUE #3214: #synth silently succeeds if given nonsense
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

The following code emits no diagnostics:
```lean
class Foo (α : Type)

variable {α : Type} (s : Missing α)

#synth Foo s
```

### Context

[Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/.23synth.20is.20ignoring.20me/near/417649900)

### Steps to Reproduce

1. Run the above code

**Expected behavior:** `#synth` should either report an info message or a failure message

**Actual behavior:** Nothing happens.

### Versions

4.5.0-rc1

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

### PR DESCRIPTION
**Pull request by leodemoura**
closes #2226
closes #3214

### CODE REVIEW

**Comment by leodemoura** [comment]
@semorrison This PR may affect Mathlib. If there are too many issues there, we should just skip it and fix the issues above when we address RFC #2452

**Comment by semorrison** [comment]
@leodemoura, the fallout in Mathlib is manageable. The only change is that we can no longer change the explicitness of a variable, and in the same line introduce a new variable that depends on it.

(I'm not sure if that is an intended or avoidable effect of this PR!)

**Comment by semorrison** [comment]
Mathlib should build now. Diff is at https://github.com/leanprover-community/mathlib4/commit/026f1b9315c058e9c0305bb832d8fc658634867e for reference.

**Comment by eric-wieser** [comment]
> The only change is that we can no longer change the explicitness of a variable, and in the same line introduce a new variable that depends on it.

This was often a footgun in mathlib anyway, as sometimes it resulted in duplicate hypotheses.

**Comment by leodemoura** [comment]
> > The only change is that we can no longer change the explicitness of a variable, and in the same line introduce a new variable that depends on it.
> 
> This was often a footgun in mathlib anyway, as sometimes it resulted in duplicate hypotheses.

Thanks for feedback. So, I will go ahead and merge the PR.

**Pull request merged**
