### PR TITLE
chore: remove unused deriving handler argument syntax

### PR DESCRIPTION
**Pull request by david-christiansen**
As far as I can tell, the ability to pass a structure instance to a deriving handler is not actually used in practice. It didn't seem to be used in the test suite, at least.

Do we want to remove this, or do we want to use and document it? This PR removes it, but that's not something I feel strongly about - but seeing if it breaks Mathlib is a useful data point.

### CODE REVIEW

**Comment by david-christiansen** [comment]
From what I can read here, the Mathlib breakage is only due to a deprecation warning being issued, and not that it doesn't compile, right?

If so, I take that as evidence that this syntax is indeed not used and can be removed.

**Comment by kim-em** [comment]
> From what I can read here, the Mathlib breakage is only due to a deprecation warning being issued, and not that it doesn't compile, right?

Right.

**Review by Kha — APPROVED** [review]

**Comment by kim-em** [comment]
Perhaps needs `master` merged? This failed on the queue.

**Comment by david-christiansen** [comment]
Thanks for the poke, @kim-em!

**Pull request merged**
