### PR TITLE
fix: only trigger TPIL build on nightly releases

### PR DESCRIPTION
**Pull request by lovettchris**
Related to https://github.com/leanprover/theorem_proving_in_lean4/pull/42

### CODE REVIEW

**Comment by Kha** [comment]
What about using a corresponding `cron:` trigger in the TPIL repo instead? I think that would scale a little nicer if we start enabling nightly CI for many repos

**Comment by lovettchris** [comment]
> What about using a corresponding `cron:` trigger in the TPIL repo instead? I think that would scale a little nicer if we start enabling nightly CI for many repos

Done.  See related PR https://github.com/leanprover/theorem_proving_in_lean4/pull/44

**Comment by lovettchris** [comment]
@Kha - why did you close the PR instead of merging the change?

**Comment by Kha** [comment]
Aah, I was confused by the PR title!

**Pull request merged**
