### PR TITLE
feat: Extensible derecursifier

### PR DESCRIPTION
**Pull request by nomeata**
This is not meant to be merged!

This branch can be used to prototype derecursifiers outside the lean4
tree. Example:

```
import Lean.Elab.PreDefinition.Main

set_option autoImplicit false

open Lean Elab

def foo (n : Nat) : Nat := match n with
  | .zero => .zero
  | .succ n => foo n
derecursify_with Structural.structuralRecursion

def derec (preDefs : Array PreDefinition) : TermElabM Unit := do
  logInfo m!"{preDefs.map (·.declName)}"
  return

def foo2 (n : Nat) : Nat := match n with
  | .zero => .zero
  | .succ n => foo2 n
derecursify_with derec
```

_Maybe_ a proper designed version of this feature is useful at some
point, see #2812 for that.

### CODE REVIEW

**Comment by nomeata** [comment]
Odd, the failing test cases say
```
  [failed to pretty print term (use 'set_option pp.rawOnError true' for raw representation)
```

Why does extending some syntax, but not even using it, affect the pretty printers?

**Comment by digama0** [comment]
Changing existing syntax generally requires an update-stage0, because stage0 syntax is used inside syntax match expressions in the stage1 compiler, meaning that it will incorrectly parse stage1 syntax which can cause a variety of random errors. You can also try setting `parseQuotWithCurrentStage` to true in `stage0/stdlib_flags.h`, which will make stage1 do its best to use stage1 syntax, although I suspect it won't work in this case because the syntax in question is builtin syntax defined in the `Lean` package rather than regular `syntax` defined in the `Init` package and used after definition.

**Comment by nomeata** [comment]
Ah, I feared it was something about bootstrapping. Thanks for the pointers!

**Comment by Kha** [comment]
> I suspect it won't work in this case because the syntax in question is builtin syntax defined in the `Lean` package rather than regular `syntax` defined in the `Init` package and used after definition.

It should work *if* the module of the quotation imports the parser

**Pull request closed without merging**
