### PR TITLE
refactor: move ir decoding helpers to separate header / implementation file

### PR DESCRIPTION
**Pull request by DanielFabian**
This is the PR we should apply.

### CODE REVIEW

**Comment by leodemoura** [comment]
!bench

**Comment by Kha** [comment]
Yeah, these accessors are all simple enough that they should just be `static inline`. We can do that when we need them in a header.

**Comment by DanielFabian** [comment]
uff, so my moving the code around causes a sizable perf regression? that's really unfortunate, sorry.

**Comment by Kha** [comment]
I'll close this for now then

**Pull request closed without merging**
