### PR TITLE
fix: forward memory and stack sizes to server

### PR DESCRIPTION
**Pull request by Vtec234**
This is to prevent file workers on resource-constrained machines from taking over all memory.

### CODE REVIEW

**Comment by Kha** [comment]
Could you remind me as to what arguments (apart from `--server`) we did *not* want to forward?

**Comment by Vtec234** [comment]
I'm not quite sure! This was #271 but there doesn't seem to be an explanation.

**Comment by Kha** [comment]
Right you are. Feel free to forward everything but `--server` :smile: .

**Comment by Vtec234** [comment]
I think all the args that make sense to forward should be forwarded now. The remaining ones are mostly of the form "print/don't print something on the command line".

**Pull request merged**
