### PR TITLE
chore: deprecate Nix-based build, remove interactive components

### PR DESCRIPTION
**Pull request by Kha**
Users who prefer the flake build should maintain it externally

### CODE REVIEW

**Comment by lenianiva** [comment]
Are all Nix components going to be removed eventually? I can take over and create a repository for the Nix build paths

**Comment by nomeata** [comment]
I expect that in the long run we certainly keep a nix shell with the build dependencies alive.

We *maybe* keep using Nix for our own CI uses, but certainly nothing that we’d want other people to import/depend upon.

So if you are motivated to maintain nix-related things in a separate repository, that would be great!

**Comment by nomeata** [comment]
It's up to you if course. But it may be easier to copy all that machinery and start taking ownership in the new repository, and adjust it to your needs.

**Comment by lenianiva** [comment]
I got one working. I'll try to support every major Lean version: https://github.com/lenianiva/lean4-nix

**Pull request merged**
