### PR TITLE
perf: issue at `binop%` and `binrel%` elaborators

### PR DESCRIPTION
**Pull request by leodemoura**
This issue was affecting several Mathlib files.

@mattrobball @semorrison This is a different solution for the issue. The comment at `Extra.lean` describes the new solution and documents the new issues found with the previous one.

closes #4085

### CODE REVIEW

**Comment by leodemoura** [comment]
Rebased on top of `nightly-with-mathlib`

**Comment by mattrobball** [comment]
Mathlib master builds locally with this cherry-picked on top of v4.8.0-rc1 without any changes. Anecdotally, it seems quite snappy.

**Comment by mattrobball** [comment]
leanprover-community/mathlib4#12742 has a benchmark run using the above. Overall -1.1T build instructions and no individual files suffered significant regressions but the wall clock was up +37%. I think the latter is anomaly. Will re-run.

**Comment by mattrobball** [comment]
Wall clock was an anomaly. Last run was neutral.

**Comment by semorrison** [comment]
(The automatic Mathlib run didn't happen because of a CI breakage induced by the std -> batteries rename. Hopefully fixed going forward by https://github.com/leanprover-community/batteries/pull/785.)

**Pull request merged**
