### PR TITLE
fix: RecursorVal.getInduct to return name of major argument’s type

### LINKED ISSUE #5661: Structure eta doesn't work for nested inductives
It is unclear if this is really a bug, or should be like this, but I’ll open an issue anyways to record this and ensuing discussion.

Lean’s type theory eta-expands structure like values when reducing, but only when using the type’s “native” recursor, not when reducing derived recursers over that type that are generated as part of nested inductives.

Small reporducer:

```
inductive StructLike α where
  | mk : α → StructLike α 

inductive Nested where
  | nest : StructLike Nested → Nested
  | other

theorem works (x : StructLike Nested) : StructLike.rec
  (motive := fun _ => Bool)
  (mk := fun _ => true)
  x = true 
  := rfl

/--
error: type mismatch
  rfl
has type
  Nested.rec_1 (fun x x => true) true (fun x x => true) x =
    Nested.rec_1 (fun x x => true) true (fun x x => true) x : Prop
but is expected to have type
  Nested.rec_1 (fun x x => true) true (fun x x => true) x = true : Prop
-/
#guard_msgs in
theorem fails (x : StructLike Nested) : Nested.rec_1
  (motive_1 := fun _ => Bool) (motive_2 := fun _ => Bool)
  (nest := fun _ _ => true)
  (other := true)
  (mk := fun _ _ => true)
  x = true 
  := rfl
```

One could argue that `Nested.rec_1` should also eta-expand the argument if needed, on the grounds that it’s really just a renamed `StructureLike.rec`.

Incidentially, #4749 would fix this.

### Versions

"4.12.0-nightly-2024-10-09"

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

### PR DESCRIPTION
**Pull request by nomeata**
Previously `RecursorVal.getInduct` would return the prefix of the
recursor’s name, which is unlikely the right value for the “derived”
recursors in nested recursion. The code using `RecursorVal.getInduct`
seems to expect the name of the inductive type of major argument here.

If we return that name, this fixes #5661.

This bug becomes more visible now that we have structural mutual
recursion.

Also, to avoid confusion, renames the function to ``getMajorInduct`.

### CODE REVIEW

**Comment by arthur-adjedj** [comment]
I've been experimenting more with nested indexed inductives, and have come around a similar issue as yours, hence the need to change that function.
I think it might be better for this to be a field in `RecursorVal`. However, I had some trouble doing that last I tried, though it shouldn't be impossible to do it. The construction of the recursor happens [here](https://github.com/leanprover/lean4/blob/a3bc4d235961bfeacf9a0ed62b01319338b2c75f/src/kernel/inductive.cpp#L1113). You would most probably want to retrieve the name of the auxiliary inductive in the RecursorVal generated by `elim_nested_inductive_result`, and then retrieve the correct inductive through `m_aux2nested`.

**Comment by nomeata** [comment]
> I think it might be better for this to be a field in `RecursorVal`. 

I thought so as well, but still let’s see what the benefits are ? Just code clarity and robustness?

(I mostly hesitated with doing it that way because of bootstrapping complications…)

**Comment by arthur-adjedj** [comment]
The benefits would mainly be a bit of performance (not needing to scroll through the type of the recursor) and robustness, the downsides would be possible bootstrapping issues, and the need for a more scrupulous reviewing, as it would change more things in the kernel. I am all for working with the implementation you've just made.

**Comment by nomeata** [comment]
I'm a bit worried about this code:

```
private def mkRecursorInfoForKernelRec (declName : Name) (val : RecursorVal) : MetaM RecursorInfo := do
  let ival ← getConstInfoInduct val.getInduct
  let numLParams    := ival.levelParams.length
  let univLevelPos  := (List.range numLParams).map RecursorUnivLevelPos.majorType
  let univLevelPos  := if val.levelParams.length == numLParams then univLevelPos else RecursorUnivLevelPos.motive :: univLevelPos
  let produceMotive := List.replicate val.numMinors true
  let paramsPos     := (List.range val.numParams).map some
  let indicesPos    := (List.range val.numIndices).map fun pos => val.numParams + pos
  let numArgs       := val.numIndices + val.numParams + val.numMinors + val.numMotives + 1
  pure {
    recursorName  := declName,
    typeName      := val.getInduct,
    univLevelPos  := univLevelPos,
    majorPos      := val.getMajorIdx,
    depElim       := true,
    recursive     := ival.isRec,
    produceMotive := produceMotive,
    paramsPos     := paramsPos,
    indicesPos    := indicesPos,
    numArgs       := numArgs
  }
```
using
```
let numLParams    := ival.levelParams.length
```
here with `ival` now from the major’s argument is probably wrong.

There is a chance that this is actually dead code anyways, and `mkRecursorInfoForKernelRec` could be dropped completely, but this needs figuring out before we can merge this.

**Pull request merged**
