### PR TITLE
fix: issue with negative integers on Mac binaries 

### PR DESCRIPTION
**Pull request by alexjbest**
~~I believe this is the correct fix based on the default C++ values of INT_MIN and INT_MAX (one is even one odd), but to be honest I don't fully understand how these bounds are meant to be used and checked.~~

This PR tries to fix the following behaviour 
```lean
theorem boom : -2147483648 + 2147483648 = 0 := by rfl
theorem boom' : -2147483648 + 2147483648 = -18446744069414584320 := by native_decide
theorem boom'' : False := by
  have := boom'
  simp [boom] at this
```
which occurs at least on a 64-bit intel mac

### CODE REVIEW

**Comment by leodemoura** [comment]
@Kha This issue affects 32-bit machines. Is there an easy way to test Lean in a 32-bit VM in our CI?

**Comment by alexjbest** [comment]
@leodemoura this is very curious actually, my machine is a recent intel mac, so it should indeed be 64 bit, and CMake detects it as such, so clearly something very odd is happening that I even hit this bug at all. I'll look into this more.

**Comment by alexjbest** [comment]
What's most likely at this point is that simply the act of building on my own machine fixed this issue for me, not the fix proposed here. The original issue appears to be a real issue affecting my 64 bit mac at least.

**Comment by leodemoura** [comment]
> What's most likely at this point is that simply the act of building lean on my own machine fixed this issue for me, not the fix proposed here. The original issue appears to be a real issue affecting my 64 bit mac at least.

@alexjbest Could you please try to build without the change?

@kha Could you please try to reproduce the bug using your Mac mini?

**Comment by alexjbest** [comment]
@leodemoura I just did this and indeed simply building master on my machine rather than using the latest Mac nightly fixes the issue for me

**Comment by leodemoura** [comment]
> @leodemoura I just did this and indeed simply building master on my machine rather than using the latest Mac nightly fixes the issue for me

Same for me.

@alexjbest Is this a new issue?

**Comment by alexjbest** [comment]
The test case I reduced this from was one I hadn't run until a few days ago so I'm not sure how far back this issue goes,

**Comment by leodemoura** [comment]
@alexjbest Could you please close the PR and create an issue?

**Comment by alexjbest** [comment]
Done, sorry for the confusion!

**Pull request closed without merging**
