### PR TITLE
fix: use withContext at ac_rfl

### PR DESCRIPTION
**Pull request by digama0**
Fixes an issue reported on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/.E2.9C.94.20ac_refl.20and.20intro).

### CODE REVIEW

**Comment by Kha** [comment]
Is there anything we can do to avoid this common footgun? Can we move it into a custom `MonadLiftT MetaM/... TacticM` instance, without incurring too much overhead?

**Comment by digama0** [comment]
Is there a reason that we can't call this right before dispatching to a `@[tactic] def` plugin? Granted, some tactics don't work on the current goal, but it seems like it would be a good default behavior.

**Comment by Kha** [comment]
If we want to do it eagerly, I think it would be best at `setGoals/...` for 100% consistency

**Comment by Kha** [comment]
For the sake of completeness, a drastically different, explicit design would be not to provide an implicit lift from `MetaM` at all but to always require an explicit lift in respect to a given goal mvar. But since we are almost always intersted in the main goal only, that might be too onerous.

**Comment by digama0** [comment]
We can't, because `withContext` is a wrapper-style tactic, and necessarily so since the relevant state is in the `Context` of the `MetaM` monad. So it would have to be done by whatever infrastructure dispatches to the user tactic. Any other solution would have the user explicitly writing the wrapper themselves, and we already have a fairly complete selection of such wrappers. To decrease the footgun propensity we would thus have to avoid functions like `getMainGoal` in favor of callback variations.

**Comment by Kha** [comment]
Right, we can't do that building on top of `MetaM`. But basing `TacticM` on top of `MetaM` even though its information partially overlaps with the goal mvars is the fundamental issue we're discussing. It should not be too hard to change `TacticM` to carry `Meta.Context` as *state* instead and then reestablish the current behavior (modulo fixing the issue at hand) via explicit lift instances.

**Pull request merged**
