### PR TITLE
doc: upstream the Lean4 pygments lexer

### PR DESCRIPTION
**Pull request by eric-wieser**
An improved `lean4` lexer is now part of pygments.

This depends on https://github.com/pygments/pygments/pull/2618 (now merged), and [a subsequent release](https://github.com/pygments/pygments/milestone/23)

### CODE REVIEW

**Comment by eric-wieser** [comment]
This isn't quite ready to be merged (as [Pygments 2.18 is not yet released](https://github.com/pygments/pygments/milestone/23)), but the new instructions already work against a development install of pygments.

**Comment by semorrison** [comment]
Marking as draft until Pygments 2.18 is released.

**Comment by eric-wieser** [comment]
Pygments has now released: https://github.com/pygments/pygments/blob/master/CHANGES

**Comment by semorrison** [comment]
Thanks! If you could rebase or merge master, hopefully CI will go through and we can merge.

**Comment by eric-wieser** [comment]
Master is now merged

awaiting-review

**Pull request merged**
