### PR TITLE
chore: benchmark new compiler

### PR DESCRIPTION
**Pull request by Kha**

### CODE REVIEW

**Comment by Kha** [comment]
!bench

**Comment by Kha** [comment]
Looks good 
image

**Comment by gebner** [comment]
Does this measure the same thing as the old metric?  From what I can tell the old one includes IR compilation as well.

**Comment by Kha** [comment]
Correct, it only measures the parts that are already there, so the two numbers should not be compared directly without keeping that in mind

**Comment by leodemoura** [comment]
Remarks:

- The new code generator is re-type-checking the code after each pass. This is useful for debugging, but we will not enable these checks by default in the future.

- The most expensive passes are already in the new code generator: `simp` and `specialize`.

**Pull request merged**
