### PR TITLE
test: lake: add env & dep cfg benchmarks + cleanup

### PR DESCRIPTION
**Pull request by tydeu**
Follow-up to  #2457 that adds a `lake env` benchmark and a configuration benchmark for a package with multiple dependencies.

### CODE REVIEW

**Comment by tydeu** [comment]
!bench

**Review by Kha — APPROVED** [review]

**Comment by tydeu** [comment]
!bench

**Comment by tydeu** [comment]
!bench

**Comment by tydeu** [comment]
!bench

**Comment by tydeu** [comment]
(The significant change is because `build no-op` now builds Inundation rather than Lean).

**Pull request merged**
