### PR TITLE
perf: globally cache intermediate type class results

### PR DESCRIPTION
**Pull request by JovanGerb**
See Zulip discussion [here](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Ways.20to.20speed.20up.20Mathlib/near/438126466)

This is a PR to determine whether this idea indeed results in faster type class search.

### CODE REVIEW

**Comment by JovanGerb** [comment]
Can anyone explain why the output on two of the tests doesn't match the expectation? These tests have nothing to do with type classes...

**Comment by nomeata** [comment]
For the reader’s convenience, the errors are
```
[00:11 (00.000835)] lean-test-stage1> --- 1616.lean.expected.out    1970-01-01 00:00:01.000000000 +0000
[00:11 (00.000537)] lean-test-stage1> +++ 1616.lean.produced.out    2024-05-13 16:12:18.608808504 +0000
[00:11 (00.000532)] lean-test-stage1> @@ -2,6 +2,16 @@
[00:11 (00.000473)] lean-test-stage1>    @Linear ?m ?m (?m :: ?m) (?m :: ?m) c.right
[00:11 (00.004419)] lean-test-stage1>  context:
[00:11 (00.000027)] lean-test-stage1>  c : Cover ?m ?m ?m
[00:11 (00.000011)] lean-test-stage1> +⊢ List ?m
…
```
and
```
 [00:46 (00.000798)] lean-test-stage1> --- omega-failure.lean.expected.out   1970-01-01 00:00:01.000000000 +0000
[00:46 (00.000555)] lean-test-stage1> +++ omega-failure.lean.produced.out   2024-05-13 16:12:52.997271237 +0000
[00:46 (00.000522)] lean-test-stage1> @@ -57,8 +57,8 @@
[00:46 (00.000507)] lean-test-stage1>    d_1 ≥ 0
[00:46 (00.000434)] lean-test-stage1>    u ≥ 0
[00:46 (00.000424)] lean-test-stage1>    t ≥ 0
[00:46 (00.000669)] lean-test-stage1> -  w ≥ 0
[00:46 (00.000428)] lean-test-stage1>    q + r + s + t + u + v + w + x + y + z + a_1 + b_1 + c_1 + d_1 + e_1 ≥ 100
[00:46 (00.000516)] lean-test-stage1> +  w ≥ 0
[00:46 (00.000425)] lean-test-stage1>    r ≥ 0
[00:46 (00.000420)] lean-test-stage1>    y ≥ 0
```

No idea, though :-)

**Comment by JovanGerb** [comment]
Out of the two errors, the second one has magically disappeared. The remaining error is a reshuffling of error messages (it doesn't look like one order is more correct than the other), in a file that seems to have nothing to do with type class search. 🤷‍♂️ Do I bench it with !bench?

**Comment by JovanGerb** [comment]
!bench

**Comment by nomeata** [comment]
!bench

On the lean repo, that command is unfortunately not available to everyone like in mathlib.

**Comment by nomeata** [comment]
!bench

**Comment by JovanGerb** [comment]
How do I interpret the benchmark results? I just see a huge wall of numbers when clicking on the link. I suppose we are most interested in mathlib times? which would have to wait for this bug to be solved: #4206

**Pull request closed without merging**
