### PR TITLE
chore: add warning comments about `findM?`

### PR DESCRIPTION
**Pull request by kim-em**

### CODE REVIEW

**Comment by semorrison** [comment]
Pinging @arthur-adjedj, just FYI.

**Comment by arthur-adjedj** [comment]
Thank you for the ping, I didn't take that into consideration when writing that function.
FYI, `occursOrInType` could be rewritten with the non-monadic `find` by passing the LocalContext to the function and fetching the type of fvars there. Doing so might be the better option compared to keeping `findM` in the codebase.

**Comment by semorrison** [comment]
> Thank you for the ping, I didn't take that into consideration when writing that function. FYI, `occursOrInType` could be rewritten with the non-monadic `find` by passing the LocalContext to the function and fetching the type of fvars there. Doing so might be the better option compared to keeping `findM` in the codebase.

If you'd be interested in doing that, I'd love to merge it. :-) `findM?` seems like a scary footgun to leave around.

**Comment by arthur-adjedj** [comment]
Right. I'm not available to work on this now, but will make an according PR to fix `occursOrInType` and to remove the monadic find by the end of the day.

**Comment by semorrison** [comment]
Obsolete given #4125.

**Pull request closed without merging**
