### PR TITLE
fix: Float RecApp out of applications

### LINKED ISSUE #2810: Superfluous parentheses can inhibit structural recursion
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

When additional parentheses are inserted around a function, this can prevent structural recursion from succeeding.

Simple example:
```lean
def f (n : Nat) : Nat :=
  match n with
  | 0 => 0
  | n + 1 => (f) n
```
With the parentheses, "structural recursion cannot be used." Replacing `(f) n` with `f n` makes it succeed. Looking at the terms `(f) n` and `f n`, the difference is whether `n` is included within the recApp metadata expression.

This behavior indirectly appeared in a Zulip question when trying to make use of structural recursion within a theorem. This is a minified example:
```lean
theorem thm (N : Nat) :
    N * 0 = 0 :=
  match N with
  | Nat.zero => rfl
  | Nat.succ n => by
    rewrite [Nat.succ_mul, Nat.add_zero]
    rw [thm]
```
Replacing `rw [thm]` with `rw [thm n]` makes structural recursion succeed -- the terms are identical except for whether `n` is included within a recApp metadata expression. Replacing `rw [thm]` by `simp only [thm]` also makes it succeed -- in this case `simp` does not create an appRec metadata expression.

### Context

[Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there-code-for-X.3F/topic/.60Nat.2Efold.60.20with.20push.20gives.20an.20exact.20size/near/399639322)

### Versions

leanprover/lean4:v4.3.0-rc1

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

### PR DESCRIPTION
**Pull request by nomeata**
This didn't work before
```
def f (n : Nat) : Nat :=
  match n with
  | 0 => 0
  | n + 1 => (f) n
```
because the `RecApp` metadata marker gets in the way. More practically
relevant, such code is to be produced when using `rw` or `simp` in
recursive theorems (see included test case).

We can fix this by preprocessing the definitions and floating the
`.mdata` marker out of applications.

For structural recursion, there already exists a `preprocess` function;
this now also floats out `.mdata` markers.

For well-founded recursion, this introduces an analogous `preprocess`
function.

Fixes #2810.

One test case output changes: With the `.mdata` out of the way, we get a
different error message. Seems fine.

Alternative approaches are:

* Leaving the `.mdata` marker where it is, and looking around it.
  Tried in #2813, but not nice (many many places where `withApp` etc.
  need to be adjusted).
* Moving the `.mdata` _inside_ the application, so that `withApp` still
  works. Tried in #2814. Also not nice, the invariant that the `.mdata`
  is around the `.const` is tedious to maintain.

### CODE REVIEW

**Comment by nomeata** [comment]
Open question: Should there be _one_ `preprocess` function invoked by `addPreDefinitions` for both strategies? Would the well-founded recursion code benefit or be hurt by the beta-reductions done for structural recursion?

**Comment by leodemoura** [comment]
> Open question: Should there be one preprocess function invoked by addPreDefinitions for both strategies? Would the well-founded recursion code benefit or be hurt by the beta-reductions done for structural recursion?

Great question. I don't see any reason why it would hurt well-founded recursion.
Let's try a single preprocess function for both of them.
Note that the current `preprocess` assumes there is only one function on the recursive block. This is not sufficient for well-founded recursion since it already supports mutual recursion. We need support for this too.

**Comment by nomeata** [comment]
>  Let's try a single preprocess function for both of them.

Will do (tomorrow)

**Comment by semorrison** [comment]
(Apologies for force pushing to your branch, I am still diagnosing some CI weirdnesses!)

**Comment by nomeata** [comment]
> Great question. I don't see any reason why it would hurt well-founded recursion.
> Let's try a single preprocess function for both of them.

Tried in #2823. Beta-reduction (if done as it is defined now) can remove `let_fun` redexes that we want to keep because of the termination argument they bring into scope; example for a test case now failing:
```
def f (p : Pos) : Pos :=
  match h : p.view with -- It would also be nice to have a feature to force Lean to applies "views" automatically for us.
  | 1 => 1
  | .succ x =>
    have : sizeOf x < sizeOf p := sizeof_lt_of_view_eq h -- See comment at `sizeof_lt_of_view_eq`
    f x + x + 1
```

Maybe one could use a more careful form of beta-reduction that works for both, but I’d say it’s not worth for the gain, and who knows, maybe the next derecursifier that comes along may need some other set of preprocessors again. 

I left a note in the code that the difference between the two functions is deliberate.

**Comment by digama0** [comment]
Note: the fact that the WF preprocessor does not remove beta redexes during preprocessing is a bug, which causes `unusedHavesSuffices` linter failures on the generated equation lemmas. Of course it is understandable due to the way WF receives hypotheses, but it should remove betas after doing the termination proofs.

**Comment by nomeata** [comment]
Thanks! That sounds indeed like you want to post-process them. Separate issue, I’d say?

**Comment by nomeata** [comment]
!bench

**Comment by nomeata** [comment]
Will merge this on Wednesday.

**Pull request merged**
