### PR TITLE
perf: issue at `binop%` and `binrel%` elaborators

### PR DESCRIPTION
**Pull request by leodemoura**
This issue was affecting several Mathlib files.

@mattrobball Found where the `[nonassignable]`s were coming from. Thanks for helping to diagnose this performance issue.

### CODE REVIEW

**Comment by mattrobball** [comment]
At leanprover-community/mathlib4#12718, I benchmarked a working mathlib with a v4.8.0-rc1 with this commit cherry picked on top. 

Overall there is a -400B in instructions driven mainly by one file which was -800B. The issue there was the new `CoeT` synthesis attempts in `Lean.Elab.Term.Op.hasCoe`.

**Comment by semorrison** [comment]
The new slow-downs are pretty severe in `Mathlib.AlgebraicGeometry.Restrict`.

**Comment by semorrison** [comment]
I got different speed center results from https://github.com/leanprover-community/mathlib4/pull/12719 that @mattrobball got from https://github.com/leanprover-community/mathlib4/pull/12718; mine are worse, with an overall +500B instructions...

**Comment by mattrobball** [comment]
It's universes triggering the expensive `CoeT`'s.

**Comment by semorrison** [comment]
Closing in favour of #4092.

**Pull request closed without merging**
