### PR TITLE
feat: add `seal` and `unseal` commands

### PR DESCRIPTION
**Pull request by leodemoura**

### CODE REVIEW

**Comment by nomeata** [comment]
Do we want/need the `seal … in $c:command` variant, and maybe also the `seal … in` variant for terms and tactics?

**Comment by leodemoura** [comment]
> Do we want/need the `seal … in $c:command` variant, and maybe also the `seal … in` variant for terms and tactics?

We already have it. See new test:
```lean
seal f in
example : f x = x + 1 := rfl
```

**Comment by nomeata** [comment]
Ah, neat! I didn't expect that after scrolling through the macro definition. Neat.

**Comment by Kha** [comment]
@nomeata `in` is a generic command combinator

**Comment by nomeata** [comment]
But I assume it won’t work scoped around terms and tactics for free, does it?
(Not urgently needed).

I’m a heavy user of `unseal` already: 
https://github.com/leanprover-community/mathlib4/compare/nightly-testing...lean-pr-testing-4061

**Pull request merged**
