### PR TITLE
Add hashable deriving.

### PR DESCRIPTION
**Pull request by DanielFabian**
Adding a deriving handler for `Hashable`. It is recursive for nested, but not recursive or mutually recursive calls.

Since It's my first PR, please check if it's ok also, if I got the place for the tests right.

### CODE REVIEW

**Comment by Kha** [comment]
FWIW, the code produced by Rust's `#[derive(Hash)]` is quite a bit simpler: it has a notion of chaining hashes (abstracted into a `Hasher` trait), then for each constructor it simply hashes the constructors index followed by its fields.

**Comment by DanielFabian** [comment]
Yes, Rust also doesn't have recursive or mutually recursive data structures. If you do the naïve thing where you delegate the hash for each field in each branch, you immediately generate a hash function that is linear in the size of the input. Which is not a property you want for a hash function.

That's why I exclude recursive and mutually recursive calls.

And if you're referring to me using primes instead of just ascending natural numbers, then that's due to the fact, that I've seen this as a pattern for your uses of `mixHash` in the code base.

**Comment by Kha** [comment]
> Yes, Rust also doesn't have recursive or mutually recursive data structures

Of course it does! You have to go through `Box` for indirection, but the hash of `Box::new(a)` ist just the hash of `a`.

> That's why I exclude recursive and mutually recursive calls.

That is not consistent with the existing implementation for [`List`](https://github.com/leanprover/lean4/blob/3db5b7e4ca12d4ea33eb982d4b7c929562f36083/src/Init/Data/Hashable.lean#L31-L32) (not sure if there are others), nor with the ones I see for Rust's collection types.

> And if you're referring to me using primes instead of just ascending natural numbers, then that's due to the fact, that I've seen this as a pattern for your uses of mixHash in the code base.

Right, I'm not saying that part in your implementation is inconsistent with the status quo. Just that we might want to align the status quo with an implementation people have probably thought about much longer than we have :) .

**Comment by DanielFabian** [comment]
> > Yes, Rust also doesn't have recursive or mutually recursive data structures
> 
> Of course it does! You have to go through `Box` for indirection, but the hash of `Box::new(a)` ist just the hash of `a`.
> 
I meant the non-`Box` version, but ok, fair enough. A struct with a `Box` is really just a wrapper to a pointer, i.e. constant size. But I get your point, because you have to explicit in Rust and are implicit in most languages.

> > And if you're referring to me using primes instead of just ascending natural numbers, then that's due to the fact, that I've seen this as a pattern for your uses of mixHash in the code base.
> 
> Right, I'm not saying that part in your implementation is inconsistent with the status quo. Just that we might want to align the status quo with an implementation people have probably thought about much longer than we have :) .

Fair enough. Want me to align to the much simpler implemenation of constructror index and straight up structural hashing?

As I said, you do lose the `O(1)` which may be quite nasty for the typical use cases of hashes like hash tables.

**Comment by DanielFabian** [comment]
I'll put the changes into separate commits, so we can drop the commit if there's any controversy ;-)

**Comment by Kha** [comment]
Could you please adhere to our [commit convention](https://leanprover.github.io/lean4/doc/commit_convention.html)?

**Comment by DanielFabian** [comment]
sure, I'll reword.

**Pull request merged**
