### PR TITLE
fix: do not ban `..` with a `.` on the next line

### PR DESCRIPTION
**Pull request by eric-wieser**
Without this change,
```lean
example : True := by
  refine' trivial ..
  . trivial
```
is a parse error.

### CODE REVIEW

**Comment by Kha** [comment]
Why is this a draft?

**Comment by eric-wieser** [comment]
It has no tests yet and the description says it should be draft if I haven't filed an issue first.

**Comment by eric-wieser** [comment]
I've added the test from the description

**Comment by Kha** [comment]
Thanks. Please add a modulo docstring to the test describing its purpose as mentioned in testing.md

**Comment by eric-wieser** [comment]
Sorry for the delay, the docstring is now present.

**Comment by eric-wieser** [comment]
awaiting-review

**Pull request merged**
