### PR TITLE
refactor: use `Except` instead of `Option` for JSON.

### PR DESCRIPTION
**Pull request by DanielFabian**
as discussed in the dev channel.

### CODE REVIEW

**Comment by Vtec234** [comment]
The build failure looks like it could be #466

**Comment by leodemoura** [comment]
> The build failure looks like it could be #466

Indeed. 

@Kha I thought the workaround you have recently added would avoid this problem for a few months. The number of exported symbols looks quite high. I am wondering whether the workaround was accidentally disabled.

**Comment by Vtec234** [comment]
Yes, I am worried the changes I introduced in CMake disabled it. I'll try building this branch on windows to make sure the option is still there.

**Comment by DanielFabian** [comment]
out of interest, how big do we expect the residual C++ to be after the compiler rewrite?

**Comment by DanielFabian** [comment]
FWIW, I don't think I somehow massively increased the number of symbols, did I?

**Comment by leodemoura** [comment]
> out of interest, how big do we expect the residual C++ to be after the compiler rewrite?

We have 3 components in C++: kernel, part of the compiler, and some constructions (https://github.com/leanprover/lean4/tree/master/src/library/constructions).
The last two will be rewritten in Lean. We are not sure about the kernel.

**Comment by Kha** [comment]
> FWIW, I don't think I somehow massively increased the number of symbols, did I?

Yes, it's more likely it's because this is the first update-stage0 after merging the Emscripten PR. Though I'm not sure what changed.

**Comment by Vtec234** [comment]
Okay, I started looking into this and then realised something. The MinGW build blows up in stage0 which is only C/C++, so the behaviour of the *current* Lean compiler is somehow irrelevant. I think the issue is that `/stage0/` contains C code which already has too many symbols in it, because it was updated via `update-stage0` on a Unix box (I'm guessing you're on one @DanielFabian?), while we only pass `-Dcompiler.extract_closed=false` when building on Windows. I think the solution would be to pass that flag always, or at least whenever we need to `update-stage0`, which unfortunately will degrade performance on all platforms. Btw, the CI failed at 66409 symbols which is just a tiny bit above 2^16. So I'm guessing it was waiting to explode and we just got unlucky with this PR's Lean changes which do introduce new closed terms.

**Comment by DanielFabian** [comment]
I sit on a windows box but either use wsl2 or ssh into a Linux machine, yep... Nix is too nice to give up, as is zsh.

**Comment by Vtec234** [comment]
I pushed a band-aid fix [here](https://github.com/Vtec234/lean4/commit/ad687be3cc9a5ae356a9edc18bbc514882ec5328) and launched CI [here](https://github.com/Vtec234/lean4/actions/runs/912896881). Let's see if it works  In any case disabling closed extraction globally seems bad. Maybe we should have a `windows-stage0` or something? But I guess overall the only real solution is #466.

**Comment by leodemoura** [comment]
> I think the solution would be to pass that flag always, or at least whenever we need to update-stage0, which unfortunately will degrade performance on all platforms.

@Vtec234 this solution is unacceptable. I wrote a lot of code that relies on this optimization. The last thing I want is to keep checking whether we are reconstructing the same object over and over again whenever we hit a performance problem. 

Another problem is that our benchmark suite is very small, and it is not useful to detect the impact of changes like this one. I lost count of how many times I have added optimizations that improved particular files but had very little impact on the benchmark suite.

If we don't find a better solution, I am willing to accept the following compromise: we rebuild using `-Dcompiler.extract_closed=false` before we perform an `update-stage0`. That is, stage0 will use the flag in all platforms, and only Windows would use it on `stage1`. Then, at least we can still benchmark with confidence without worrying whether we are reconstructing the same object all the time.

I do hope we find a better workaround.

**Comment by Vtec234** [comment]
Would getting the `__declspec(dllexport)` (or some such) markers to work properly solve the issue? Are the closed terms needed as `Externs` by the interpreter or as symbols which we otherwise need to resolve dynamically? If not, hiding them from the export tables seems like it would be independently useful and could perhaps defer the need to cut the knot between libleancpp and libInit/Std/Lean.

**Comment by leodemoura** [comment]
> Would getting the `__declspec(dllexport)` (or some such) markers to work properly solve the issue? Are the closed terms needed as `Externs` by the interpreter or as symbols which we otherwise need to resolve dynamically? If not, hiding them from the export tables seems like it would be independently useful and could perhaps defer the need to cut the knot between libleancpp and libInit/Std/Lean.

I think Sebastian has tried this and it didn't work.

**Comment by leodemoura** [comment]
I found a workaround that saves 24k symbols. It is ugly, but it is good enough for now. Instead of creating initialization functions for closed terms, I am creating C macros. I am testing it, and will push if there are no problems.

**Comment by leodemoura** [comment]
I pushed the change. Let's see if we can build the Windows binary with it. If it works, @DanielFabian could you please rebase your PR on top of it? You will have to redo the `update-stage0` steps.

**Comment by leodemoura** [comment]
Here is the hack in action https://github.com/leanprover/lean4/commit/5069c82581e3e06f6a87d8efb6c33f09e499c4f3

**Comment by leodemoura** [comment]
It didn't work :(
I just recalled that the init functions were `static`, and were not being exported anyway.
I am going to destructively revert this change since the hack is ugly and didn't help.

**Comment by leodemoura** [comment]
I tried another workaround: marking the auxiliary constants for closed terms as `static`. 
It is looking more promising. The CI already managed to build the stage0 binary on Windows.

**Comment by leodemoura** [comment]
It worked. Got a green on the Windows build :)

@DanielFabian could you please rebase your PR on top of the new master? It should work now.

**Comment by DanielFabian** [comment]
@leodemoura done, let's see if the build will be green...

**Comment by Kha** [comment]
@leodemoura Thanks for figuring out a workaround! It is reassuring to see that while it did impact C code generation, total compilation time and binary size actually went down: http://speedcenter.informatik.kit.edu/velcom/run-detail/7b2753f1-47d2-4930-bff7-d326eaf3f5ff. After all, sharing closed terms across modules would also negatively impact separate compilation under the module system.

**Comment by Kha** [comment]
@DanielFabian I'm almost afraid to ask, but shouldn't `fromJson?` be called `fromJson` now? We only use the `?` suffix for `Option`. But maybe we shouldn't :) .

**Comment by DanielFabian** [comment]
To me at least, `Except` is a more expressive `Option` in the context like it's used here. `fromJson` sounds less uncertain than `fromJson?` which this change surely didn't accomplish.

I'm not super convinced that the naming convention `?` is that great because it feels a lot like the `?.` operator in type script or c#... And it behaves much in the same way. But if we already use it, at least I personally wouldn't see a problem of using `?` also for `Except`. 

You are denoting that you expect the result to return or not. The fact that the error case carries information feels completely immaterial in this context. Also `toJson` is supposed to always work and `fromJson?` not, so that's another discrepancy which makes the `?` warranted to me...

What do you reckon?

**Comment by Kha** [comment]
I suppose it depends on whether we see `Except` as data or an effect. We don't want to add `?` to every monadic function that may throw an exception. On the other hand, if `Option` is not a monad, it seems like `Except` shouldn't be one either. I don't know. @leodemoura Perhaps something to discuss in a new dev meeting?

**Comment by Kha** [comment]
While not directly related to our `?`, I should remark that Rust's `?` suffix operator works with both types.

**Comment by Kha** [comment]
Fwiw, this is the number of public symbols before and after the change (measured from Linux, so it was above the Windows limit before):
```bash
$ for c in upstream/master~3 upstream/master; do export c=$(git rev-parse $c); nix shell .\?rev=$c#lean -c bash -c 'echo -en "$c "; nm --defined-only --extern-only $(which lean) | wc -l'; done
e8a958d8f363a8c56c1937a4e2c18ff9084b2060 70971
3ff7df3675bef6b7791cb86fa4793097cd8b9c0b 49464
```
Btw, can I say how awesome it is that I can measure this fetching only the `lean` binaries (no stdlib) from CI without any local building :grin: ? You just have to be careful to specify only commits that actually went through CI...

**Comment by DanielFabian** [comment]
lol, sounds like you've got too warm in your room or too weak a machine, 😆

**Comment by DanielFabian** [comment]
(FYI, this kind of stuff, I'm hoping is something we can replicate in lake... Cloud caches FTW.)

**Comment by Kha** [comment]
Let's merge this for now so it doesn't bit rot.

**Comment by leodemoura** [comment]
> I suppose it depends on whether we see `Except` as data or an effect. We don't want to add `?` to every monadic function that may throw an exception. On the other hand, if `Option` is not a monad, it seems like `Except` shouldn't be one either. I don't know. @leodemoura Perhaps something to discuss in a new dev meeting?

Yes, we should discuss this in the next dev meeting.

**Pull request merged**
