### PR TITLE
fix: add local Hashable instance

### PR DESCRIPTION
**Pull request by ydewit**
When inductives are (indirectly) mutually recursive, say `inductive T | t (args: List T)` instead of `inductive T | t (arg : T)`, Lean would fail to find an instance of Hashable for `T` because it was not yet defined.

This commit makes sure that the deriving handler adds a needed Hashable T instance to the local scope so that Hashable.hash can be resolved recursively.

### CODE REVIEW

**Comment by leodemoura** [comment]
Could you please add tests for the issue being fixed?
It would also be nice to have comments explaining the change.

**Comment by digama0** [comment]
you should also put "fixes #1737" in the PR description or commit comment if it is intended to address/close an issue.

**Comment by ydewit** [comment]
> you should also put "fixes #1737" in the PR description or commit comment if it is intended to address/close an issue.

Sure, will do! I actually took a quick peek at the recent commits and followed what I saw there: `fix: .. (#????)`.

**Comment by Kha** [comment]
The reference in the commit title is a PR number from squashing, not the issue number

**Pull request merged**
