### PR TITLE
fix: include NUL characters on calls to getLine

### LINKED ISSUE #3546: null characters break `readFile`/`getLine`
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

Null characters break `IO.FS.readFile`  /  `IO.FS.Handle.getLine`. The null character will trim lines to the null character because of the C implementation of `getLine`. The implementation uses the null-terminated output of `fgets` rather than the buffer to and uses  the null-terminated C string `lean_mk_string` instead of `lean_mk_string_from_bytes` to construct the string. This *is* mentioned in the C docstring of `getLine` (but not in the Lean one). Nonetheless, this is an undesirable behavior.

https://github.com/leanprover/lean4/blob/0362fcea699e55b966c897b240c520f579da7a35/src/runtime/io.cpp#L464-L495

### Steps to Reproduce

```lean
def test : IO Unit := do
  let tmpFile := "readLineBug.tmp"
  let s := "foo\u0000bar"
  IO.FS.writeFile tmpFile s
  IO.println <| ← IO.FS.readFile tmpFile

#eval test -- foo
```

**Expected behavior:**

`IO.FS.readFile` should read a whole file as a `String` including null characters.

**Actual behavior:**

`IO.FS.readFile` does not properly read lines including null characters.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

### PR DESCRIPTION
**Pull request by axionbuster**
Fixes #3546 ("null characters break `readFile`/`getLine`").

This draft pull request showcases an implementation of `getLine` that would not truncate on the first occurrence of the NUL character (`\0`) and properly seek the newline character (assuming text mode) in case users expect `getLine` to preserve NUL characters in text input.

However, I was concerned that some parts of the Lean runtime might expect NUL-terminated strings. I am new to the codebase, so I'm not sure.

The repeated calls to `ungetc` may negatively affect performance. I'm not sure about this approach, either. I'm open to discussions.

### CODE REVIEW

**Comment by axionbuster** [comment]
The test has apparently stalled; I cannot stop it.

**Comment by axionbuster** [comment]
@joehendrix hello. A stalled CI test has been running for a few hours. I thought that I had to let someone know.

**Comment by axionbuster** [comment]
It passes all the tests. The test that failed on my computer was apparently known to fail on macOS.

**Comment by Kha** [comment]
Thanks for your contribution but fgetc seems unlikely to make for a satisfactory solution. We should first analyze what Rust does, probably.

**Comment by axionbuster** [comment]
> Thanks for your contribution but fgetc seems unlikely to make for a satisfactory solution. We should first analyze what Rust does, probably.

The way it's done in Rust is similar to the original code: In the original code in the Lean library, a bulk of text input is first fetched in a buffer (done by `fgets`). The C library will cut off the buffer where it fits the buffer's capacity, or the last character in the buffer contains the NUL character or the line feed (`\n`) character. Many buffers are copied and then concatenated to assemble a contiguous string representing a line.

The difference between the Rust and C implementations is that the Rust library does not specially treat the NUL character. On the other hand, in C, the NUL character is used as a sentry to mark the end of the string; in other words, it believes that the stream input is NUL terminated. In addition, it does not otherwise indicate the number of bytes read.

To accomplish the goal of preserving NUL characters in the input string, I considered a couple of approaches:

1. Use `fread` and rewind the buffer manually using `fseek`: Ignore NUL characters (`fread`). Otherwise, if a line feed is detected, advance the buffer by the difference between the index of the earliest line feed character and the actual length of the buffer. Unfortunately, if the file is opened in "text mode," then `fseek` cannot be used (except with the unmodified values returned from a call to `ftell`). If the file is not on disk, then `fseek` is meaningless. Also, for portability on Windows, the file must be either opened in text mode (to convert carriage return-line feed to line feed) or the compound string `\r\n` must be searched for in the buffer, including in the case where `\r` and `\n` are split into disjoint buffers.
2. Use `fread` and rewind the buffer using `ungetc`: `ungetc` works for all C files (including devices and streams), but it may only be called at most once after a successful read or up to an implementation-defined limit (typically very short), whichever is larger.
3. Use `fgets`. If it returns a string with precisely one byte (it should be the NUL character, right?), append that single-character string and try again. I haven't given this approach much thought until now. I could test it.
4. Use `fgetc` many times. I was worried that this approach would be slow, but, to my surprise, it wasn't ... unbearable (on my local computer against the standard input stream). Maybe (?) I can assume that the stream is buffered by the C/C++ library (or maybe not). Though the PR check ran slower than the others, it could have been an hour-of-day effect when GitHub's computers were congested. I'll have to see if I can run any relevant benchmarks.
5. Implement a buffered I/O system. Probably a no-go.

Thank you for your feedback, and don't hesitate to tell me what you think.

**Comment by Kha** [comment]
Thanks for the analysis. Since the original issue is about `readFile`, I believe the right course of action is to implement `readFile` independently of `getLine`, which it really should be anyway.

**Comment by axionbuster** [comment]
I understand. The implementation of `readFile` (specifically, `readToEnd`) calls `getLine` repeatedly to construct a buffer for the file, which I thought should be reformed anyway.

**Comment by axionbuster** [comment]
While I was reading the `IO.lean` source file, I realized I had several questions:

https://github.com/leanprover/lean4/blob/466ef74ccc024e334e9c78d9e008d3f7612f9ccf/src/Init/System/IO.lean#L422-L460

- Why are there different functions for text and binary modes? In the C library, the difference is included in the file handle itself, and users do not need to distinguish between using one type of function over another.
- Would it make sense to tie the ability to translate line endings to the operating system running the program in `lines`? Assuming the interface is independent of the C library, shouldn't the user be able to choose between the two approaches?

Right now, there seem to be text and binary mode functions solely because of line endings. Perhaps it would be more appropriate to use binary mode functions only, read the input, and then translate the line endings in bulk according to the platform. If the input buffer is clipped between `\r` and `\n` on Windows, one more byte must be read to determine it. Then, there's the issue: "What if there's an `\r` but no paired `\n`, whether due to EOF or not?"

Another issue is this: "Would there ever be a case where a stream could EOF but resume later?" If the answer is "yes," then, lest buffered I/O be implemented in Lean itself, either (1) the file must be opened in text mode in the C library or (2) any unpaired `\r` must be discarded, to avoid the tragic case of EOF happening right in between `\r` and `\n` and that case being untranslated. If the answer is "no" today, it could become "yes" tomorrow. Would this be a behavior change, or is it not relevant?

I am considering the following steps:

- Keep using my current implementation of `getLine` because the old implementation is "incorrect" (if preserving NUL characters is required), and I haven't found a better approach that doesn't require a more significant change. I also had trouble trying to run the benchmarks.
- Modify the bulk text input and output functions to use the binary file primitives underneath. If the platform is Windows, translate the line endings. Otherwise, do not process the buffer any further.
- While translating the line endings on Windows, uniformly discard `\r`.

Any feedback would be appreciated.

**Comment by Kha** [comment]
We never use text mode: d85a4f5495a60a528befca9a2e77d461c2fbf918. We have two functions for reading raw binary data and for valid Unicode text.

**Comment by axionbuster** [comment]
> We never use text mode: [d85a4f5](https://github.com/leanprover/lean4/commit/d85a4f5495a60a528befca9a2e77d461c2fbf918). We have two functions for reading raw binary data and for valid Unicode text.

I get it. (And sorry for the late reply.) Here, I've made some changes to my plan and drafted a UTF-8 validation function.

**Pull request closed without merging**
