### PR TITLE
Compile against glibc 2.26

### PR DESCRIPTION
**Pull request by Kha**

### CODE REVIEW

**Comment by Kha** [comment]
Yikes, the ARM CI jobs were not registered as mandatory checks yet...

**Comment by digama0** [comment]
The ARM jobs are cross-compiles, so I don't think they can be easily tested.

**Comment by Kha** [comment]
They should at least build though

**Comment by Kha** [comment]
Reverted in https://github.com/leanprover/lean4/commit/a3ebfe29ea516e45dba97dfd303cfc11cc47ff04

**Comment by gebner** [comment]
> The ARM jobs are cross-compiles, so I don't think they can be easily tested.

@digama0 It's fairly easy to run them under qemu:
https://github.com/leanprover/lean4/pull/1913

Unfortunately emulation is too slow to run all tests, but we should probably still run a subset.  Feel free to take over that PR if you want.

**Pull request merged**
