### PR TITLE
fix: macro scopes in Conv.congr

### PR DESCRIPTION
**Pull request by digama0**
As [reported on Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/server.20error/near/315845493).

### CODE REVIEW

**Comment by Kha** [comment]
Missing test output?

**Comment by digama0** [comment]
it takes me 20 minutes to run the test anyway... I believe the test should result in no change to the output so I'm just optimistically running CI.

**Comment by Kha** [comment]
Ah, wouldn't it be nicer though to also test that the goal tag looks as expected?

**Comment by digama0** [comment]
well it's a hygienic name anyway, so it's hard to test that it has the right scopes. This is an edge case anyway, so I'm happy as long as it doesn't panic.

**Comment by Kha** [comment]
It's not hygiened anymore after `appendTag`!

**Comment by digama0** [comment]
it should still be hygienic, with the same macro scopes as the original case tag. The bug occurs when you have both a hygienic base tag and want to append a hygienic field name to it. With the fix, the field name is no longer hygienic but the base tag still is, so you get a hygienic result.

**Comment by Kha** [comment]
No, I don't think goal tags are supposed to ever be hygienic, that's why `appendTag` is defined that way. 
image

**Pull request merged**
