### PR TITLE
Build, test & bundle Lake

### PR DESCRIPTION
**Pull request by Kha**
TODO:
* [ ] adjust docs
* [ ] ...

Support in the Nix setup is TBD after Nix gets proper submodule treatment :grimacing:

### CODE REVIEW

**Comment by Kha** [comment]
@tydeu Any idea on the Windows test failure?

**Comment by tydeu** [comment]
@Kha it is kind of hard to debug this without access to the build results (especially as it neither occurs on my machine or my CI). 😆

**Comment by tydeu** [comment]
@Kha My first guess at the error would be that it almost looks like `leanc` is missing.

**Comment by tydeu** [comment]
I went ahead and downloaded the build results and ran `make test` with `LAKE` set to the built Lake and it ran successfully (on my Windows machine).

**Comment by Kha** [comment]
Oh, haha, it must work for you because your `leanc` is a binary - from elan. I was planning to rewrite `leanc` in Lean anyway, which will fix this.

**Comment by tydeu** [comment]
@Kha On a different note, why are running `make clean` and then `make test`?  All the Lake tests clean the their outputs before running their test.

**Comment by Kha** [comment]
Ah. Hm. I guess I didn't expect that.

**Comment by tydeu** [comment]
@Kha Well, it *is* a build system test -- the test not very useful if the build output is already there (unless that is the special case being tested). 😆

**Comment by tydeu** [comment]
@Kha I just went ahead and release proper version 2.1.0 of Lake, so that you can pin the submodule at that tag/version rather than to a prerelease.

**Comment by lovettchris** [comment]
I feel like a github submodule for lake is going to be a bit of a pain, is it really necessary to maintain Lake in a separate repo?  WIth lean 4 evolving so fast I worry the Lake PR's will get a bit tricky... Breaking change in lean4, but lean4 is building lake via submodule, so submodule needs to be updated, but you can't build that yet until the new lean4 is out, which you can't build yet because...

**Comment by tydeu** [comment]
@lovettchris doesn't as submodule make that easier? I.e., if necessary Lean can update the submodule code to make the Lean build happy, and then can PR to the main Lake repo so it can be merged when the new Lean is released.

**Comment by tydeu** [comment]
@Kha one question I do have is: how are Lake submodule update going to be done. Will it be an intermittent `chore` like `update stage0` or will it happen according to some scheduled CI job (e.g., along with each nightly release)?

**Comment by Kha** [comment]
I didn't have any automation in mind. I assumed you would open a PR whenever you want new changes to be distributed and we would merge it no questions asked.

**Comment by Kha** [comment]
This is also assuming that after an initial active phase, Lake development might quiet down a bit, much like with elan. Until the next big feature like cloud building at least :) .

**Comment by tydeu** [comment]
@Kha okay, sounds good!

**Comment by tydeu** [comment]
@Kha fyi, this PR is currently replaces today's functional JSON server code with yesterday's buggy code. That should probably be fixed.

**Comment by Kha** [comment]
Yeah, somehow I made a mess when moving LeanPaths to master while switching machines... to be honest, if I'd known that you had already implemented `print-paths` without LeanPaths, I wouldn't have bothered with that :) . I hope it's good now.

**Comment by tydeu** [comment]
@Kha yep, server is working on a basic package now! 😄 Sorry for all the trouble my suggestion caused. 😢

**Comment by Kha** [comment]
Hmm, looks like that broke something. But only in one Linux CI job?

**Comment by Kha** [comment]
That job is using an older clang

**Comment by Kha** [comment]
Thanks. @leodemoura This should be ready for merge.

**Comment by tydeu** [comment]
@Kha Lake should probably be updated once more (so that its JSON fix is also included).

**Pull request merged**
