### PR TITLE
feat: add `simp` configuration option `Simp.Config.instances`

### PR DESCRIPTION
**Pull request by leodemoura**
Depends on #3124

Mathlib adaptation PR is at https://github.com/leanprover-community/mathlib4/pull/9572

### CODE REVIEW

**Comment by leodemoura** [comment]
!bench

**Comment by semorrison** [comment]
This does cause [a variety of Mathlib failures](https://github.com/leanprover-community/mathlib4/actions/runs/7455698520). Can we start out with this defaulting to true?

**Comment by semorrison** [comment]
I've created a discussion on [zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Proposed.20change.20to.20simplifier.3A.20don't.20simplify.20instances/near/411873655) to forewarn users about this, and to discuss impact.

**Comment by semorrison** [comment]
This PR was superseded by #3507.

**Pull request closed without merging**
