### PR TITLE
fix: ac_nf0, simp_arith: don't tempt the kernel to reduce atoms

### LINKED ISSUE #5384: unwanted reduction when checking simp_arith proof objects
This was originally reported as [#7729](https://github.com/leanprover-community/mathlib4/issues/7729) on mathlib4 by @digama0, but is actually a lean bug.

When the kernel checks the proof produced by `simp_arith` it is prone to start evaluating atoms that it shouldn’t and neend’t evaluate.

```lean
-- A function that reduced badly, as a canary for kernel reduction
def bad (n : Nat) : Nat :=
  if h : n = 0 then 0 else bad (n / 2)
termination_by n

-- this is fast:

/-- info: time: 11ms -/
#guard_msgs in
#time
theorem bar (n : Nat) : 2 * n = n + n := by simp_arith

-- this is slow:

/-- info: time: 311ms -/
#guard_msgs in #time
theorem foo : 2 * bad 100 = bad 100 + bad 100 := by simp_arith

-- the profiler tells us that the time is spent in kernel reduction

-- these are the proof terms produced:

/-- info: time: 13ms -/
#guard_msgs in
#time
theorem bar' : ∀ (n : Nat), 2 * n = n + n :=
  fun n =>
  of_eq_true
    (Nat.Linear.ExprCnstr.eq_true_of_isValid [n]
      { eq := true, lhs := Nat.Linear.Expr.mulL 2 (Nat.Linear.Expr.var 0),
        rhs := (Nat.Linear.Expr.var 0).add (Nat.Linear.Expr.var 0) }
      (Eq.refl true))

/-- info: time: 335ms -/
#guard_msgs in
#time
theorem foo' : 2 * bad 100 = bad 100 + bad 100 :=
  of_eq_true
    (Nat.Linear.ExprCnstr.eq_true_of_isValid [bad 100]
      { eq := true, lhs := Nat.Linear.Expr.mulL 2 (Nat.Linear.Expr.var 0),
        rhs := (Nat.Linear.Expr.var 0).add (Nat.Linear.Expr.var 0) }
      (Eq.refl true))

-- A possible fix could be to abstract the proof over the atoms, and use an `id`, 
-- and fingers crossed that the kernel checks the proof in the right way:

/-- info: time: 15ms -/
#guard_msgs in
#time
theorem foo'fix : 2 * bad 100 = bad 100 + bad 100 :=
  @id (∀ (n : Nat), 2 * n = n + n)
    (fun x1 => of_eq_true
    (Nat.Linear.ExprCnstr.eq_true_of_isValid [x1]
      { eq := true, lhs := Nat.Linear.Expr.mulL 2 (Nat.Linear.Expr.var 0),
        rhs := (Nat.Linear.Expr.var 0).add (Nat.Linear.Expr.var 0) }
      (Eq.refl true))) (bad 100)

-- NB: This does not help.

/-- info: time: 313ms -/
#guard_msgs in
#time
theorem baz : 2 * bad 100 = bad 100 + bad 100 := by
  generalize bad 100 = x
  simp_arith
```

It’s unclear to me how often that happens in practice. It does not seem to affect `omega` in the same way, so maybe low priority.

### Versions

"4.12.0-rc1"

### Additional Information

[Additional information, configuration or data that might be necessary to reproduce the issue]

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

### LINKED ISSUE #5699: kernel hangs on ac_nf expression
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

The following test case hangs in the kernel

```lean
axiom foo {p : Prop} {x : BitVec 32} (h : (!x == x + 0#32) = true) : p

theorem add_eq_sub_not_sub_one (x : BitVec 32) (h : (!x == x + (1#32 + 4294967295#32)) = true) : False := by
  simp only [BitVec.reduceAdd] at h
  exact foo h -- this works

theorem add_eq_sub_not_sub_one' (x : BitVec 32) (h : (!x == x + 1#32 + 4294967295#32) = true) : False := by
  ac_nf0 at h
  simp only [BitVec.reduceAdd] at h
  exact foo h -- this hangs here
```

### Context

This issue arose when testing bv_decide with `ac_nf` enabled. 

### Steps to Reproduce

1. Copy into Lean
2. Wait for it to run
3. Observe yellow line next to `exact foo h` not disappearing 

**Expected behavior:** Proof should be confirmed by kernel

**Actual behavior:** Kernel is hanging

### Versions

"4.12.0, commit 225e08965d644715e8961cd205ffedf1cf7d24c2"

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

### PR DESCRIPTION
**Pull request by nomeata**
this fixes #5699 and fixes #5384.

### CODE REVIEW

**Comment by nomeata** [comment]
This breaks handling of neutrals, it seems. Will need to have a closer look.

**Comment by nomeata** [comment]
Is this tactic unused in mathlib? I am surprised mathlib CI passed before my latest commit!

**Comment by bollu** [comment]
@nomeata do you think a similar issue could be behind omega's mysterious slowdowns with subtraction with made us change `toNat_sub` to `toNat_sub'` (https://github.com/leanprover/lean4/blob/master/src/Init/Data/BitVec/Lemmas.lean#L1977-L1982), with the test case here(https://github.com/leanprover/lean4/blob/master/tests/lean/run/omega.lean#L492-L505), inlined below:

```lean
-- This example, reported from LNSym,
-- started failing when we changed the definition of `Fin.sub` in https://github.com/leanprover/lean4/pull/4421.
-- When we use the new definition, `omega` produces a proof term that the kernel is very slow on.
-- To work around this for now, I've removed `BitVec.toNat_sub` from the `bv_toNat` simp set,
-- and replaced it with `BitVec.toNat_sub'` which uses the old definition for subtraction.
-- This is only a workaround, and I would like to understand why the term chokes the kernel.
example
    (n : Nat)
    (addr2 addr1 : BitVec 64)
    (h0 : n ≤ 18446744073709551616)
    (h1 : addr2 + 18446744073709551615#64 - addr1 ≤ BitVec.ofNat 64 (n - 1))
    (h2 : addr2 - addr1 ≤ addr2 + 18446744073709551615#64 - addr1) :
    n = 18446744073709551616 := by
  bv_omega
```

**Comment by nomeata** [comment]
That’s somewhat likely. In general, the test I would apply here: If the runtime changes if you change the constants, although the proof terms look otherwise the same, then the kernel is looking at the atoms of the proof when it shouldn’t.

Do we have an actual not-worked-around issue with `omega` to investigate?

**Pull request merged**
