### PR TITLE
typo

### PR DESCRIPTION
**Pull request by richardkiss**
# Read this section before submitting

* Ensure your PR follows the [External Contribution Guidelines](https://github.com/leanprover/lean4/blob/master/CONTRIBUTING.md).
* Please make sure the PR has excellent documentation and tests. If we label it `missing documentation` or `missing tests` then it needs fixing!
* Include the link to your `RFC` or `bug` issue in the description.
* If the issue does not already have approval from a developer, submit the PR as draft.
* The PR title/description will become the commit message. Keep it up-to-date as the PR evolves.
* If you rebase your PR onto `nightly-with-mathlib` then CI will test Mathlib against your PR.
* You can manage the `awaiting-review`, `awaiting-author`, and `WIP` labels yourself, by writing a comment containing one of these labels on its own line.
* Remove this section, up to and including the `---` before submitting.

---

Closes #0000 (`RFC` or `bug` issue number fixed by this PR, if any)

### CODE REVIEW

**Comment by nomeata** [comment]
Thanks! I'm about to change that docstring in #4542 anyways, would you mind copyediting my docstring changes there instead?

**Comment by richardkiss** [comment]
> Thanks! I'm about to change that docstring in #4542 anyways, would you mind copyediting my docstring changes there instead?

Yes, I can do that.

> Thanks! I'm about to change that docstring in #4542 anyways, would you mind copyediting my docstring changes there instead?

You bet. Tag me in that thread or here when you want me to look at it.

**Comment by nomeata** [comment]
Just go ahead over there, ideally using the “suggested edit” feature.

**Comment by richardkiss** [comment]
Applied in https://github.com/leanprover/lean4/pull/4542

**Pull request closed without merging**
