### PR TITLE
fix(runtime/mpz): finish LLP64 support

### PR DESCRIPTION
**Pull request by Kha**

### CODE REVIEW

**Comment by Kha** [comment]
Great, now it's working on Windows but failing on macOS, presumably because `libc++` defines `size_t` as `unsigned long` instead of `unsigned long long`, and it can't decide between the `unsigned` and `unsigned long long` (`uint64`) overloads. @leodemoura Any ideas on how to solve this mess?

**Comment by Kha** [comment]
In theory, having exactly one overload for `uint32` (`unsigned`) and one for `uint64` (`unsigned long long`) on any platform like here sounds like the only reasonable setup for me. In practice, `libc++`'s `size_t` breaks this.

**Comment by leodemoura** [comment]
Yes, this stuff is a mess. I can work around the issue at `instance.cpp` and avoid this problem. It is not a perfect solution, but it makes sure we can build on all platforms. Then, we just drop this PR.

**Comment by Kha** [comment]
Ok, thanks!

**Comment by Kha** [comment]
Feel free to cherry-pick https://github.com/leanprover/lean4/pull/35/commits/dadc5e3856e2652fd2e8292c47fd84d60fe6ac4c though :)

**Comment by leodemoura** [comment]
> Feel free to cherry-pick [dadc5e3](https://github.com/leanprover/lean4/commit/dadc5e3856e2652fd2e8292c47fd84d60fe6ac4c) though :)

I missed this commit :( 
I had to do something similar to fix the Windows build.

**Pull request closed without merging**
