### PR TITLE
doc: document how to set lean's build options with CMake

### LINKED ISSUE #2086: [cmake] feature flags not declared public
### Description

The feature flags are not visible in `cmake-gui` or `make edit_cache`.

They are visible in `build_dir/stage1` though, just not in `build_dir`.

### Steps to Reproduce

1. `cmake .....`
2. In build directory, `make edit_cache`

**Expected behavior:** Should see options specific to lean4

**Actual behavior:** No special options

### Versions
Lean (version 4.0.0, commit 4b974fd60b9f, Release)

### PR DESCRIPTION
**Pull request by iacore**
Closes #2086

### CODE REVIEW

**Comment by Kha** [comment]
The only supported way of setting CMake variables is as part of the initial `cmake` call as documented below in that file, otherwise we'll get into trouble with forwarding them to the correct stages. Lean very much is not a standard CMake project.

**Comment by locriacyber** [comment]
There is no documentation of how to do that

**Comment by hargoniX** [comment]
It's written right below in that file how to set CMake options isnt it? And on top of that even a couple of interesting ones specific to the Lean project.

**Comment by locriacyber** [comment]
I mean like `LLVM=ON`. Those options are available with `make edit_cache` and in the CMake GUI.

**Pull request closed without merging**
