### PR TITLE
cmdline benchmarking suite

### PR DESCRIPTION
**Pull request by Kha**
@leodemoura I documented how to setup the suite and a basic workflow below, please give it a try. The `temci` tool seems to work on macOS at least when using Nix, but I haven't tried it without Nix yet.

### CODE REVIEW

**Comment by leodemoura** [comment]
I got the following error:
```
~/projects/lean4/library $ pip install pip3 install git+https://github.com/parttimenerd/temci.git
Downloading/unpacking git+https://github.com/parttimenerd/temci.git
  Cloning https://github.com/parttimenerd/temci.git to /tmp/pip-ZEhBAu-build
  Running setup.py egg_info for package from git+https://github.com/parttimenerd/temci.git
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/tmp/pip-ZEhBAu-build/setup.py", line 10, in <module>
        with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/tmp/pip-ZEhBAu-build/setup.py", line 10, in <module>

    with open(path.join(here, 'README.rst'), encoding='utf-8') as f:

TypeError: 'encoding' is an invalid keyword argument for this function

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /home/leo/.pip/pip.log
```

**Comment by Kha** [comment]
> `$ pip install pip3 install`

Sorry, that should be just `pip3 install`. I'm very surprised it tried to do anything at all when called like that.

**Comment by leodemoura** [comment]
It seems I need to upgrade Python :)

```
sudo pip install pip3 install git+https://github.com/parttimenerd/temci.git
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
WARNING: The directory '/Users/leonardodemoura/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/Users/leonardodemoura/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/parttimenerd/temci.git
  Cloning https://github.com/parttimenerd/temci.git to /private/tmp/pip-req-build-0Yvnw5
  Running command git clone -q https://github.com/parttimenerd/temci.git /private/tmp/pip-req-build-0Yvnw5
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-0Yvnw5/setup.py", line 10, in <module>
        with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-req-build-0Yvnw5/
```

**Comment by Kha** [comment]
So it should be
```
pip3 install git+https://github.com/parttimenerd/temci.git
```
if you don't have `pip3`, or not even `python3`, then yes, you will need to upgrade :) . Or use Nix :grin: .

**Comment by leodemoura** [comment]
I installed python3, and then `temci` (I think). Here is the log
```
~/projects/lean4 (master)$ sudo pip3 install git+https://github.com/parttimenerd/temci.git
The directory '/Users/leonardodemoura/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/leonardodemoura/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/parttimenerd/temci.git
  Cloning https://github.com/parttimenerd/temci.git to /private/tmp/pip-req-build-6drjk87l
Collecting click@ https://github.com/pallets/click/archive/f537a208591088499b388b06b2aca4efd5445119.zip from https://github.com/pallets/click/archive/f537a208591088499b388b06b2aca4efd5445119.zip (from temci==0.7.13)
  Downloading https://github.com/pallets/click/archive/f537a208591088499b388b06b2aca4efd5445119.zip
     | 2.4MB 88.1MB/s
Collecting humanfriendly (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/90/df/88bff450f333114680698dc4aac7506ff7cab164b794461906de31998665/humanfriendly-4.18-py2.py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 6.4MB/s 
Collecting pytimeparse (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/1b/b4/afd75551a3b910abd1d922dbd45e49e5deeb4d47dc50209ce489ba9844dd/pytimeparse-1.1.8-py2.py3-none-any.whl
Collecting fn (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/a2/32/9d184dc2e8225af558e155a3865d610df8533d5d48a2ed5943bf8a30a137/fn-0.4.3.tar.gz
Collecting cpuset-py3 (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/9d/01/6bc526384a88a511aba163b265c91a8a75b9f0b2224633b063094ef583a1/cpuset_py3-1.0.1-py3-none-any.whl (116kB)
    100% |████████████████████████████████| 122kB 1.2MB/s 
Collecting wcwidth (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting rainbow_logging_handler (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/3d/15/aa3cd5c46c709b2bc45e3f8612b6484bbc869d43f92dfc4a86b65e6a240a/rainbow_logging_handler-2.2.2.zip
Collecting tablib (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/7b/c7/cb74031b330cd94f3580926dc707d148b4ba9138449fc9f433cb79e640d8/tablib-0.13.0-py3-none-any.whl (75kB)
    100% |████████████████████████████████| 81kB 8.9MB/s 
Collecting pyyaml (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/a3/65/837fefac7475963d1eccf4aa684c23b95aa6c1d033a2c5965ccb11e22623/PyYAML-5.1.1.tar.gz (274kB)
    100% |████████████████████████████████| 276kB 1.2MB/s 
Collecting seaborn (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/a8/76/220ba4420459d9c4c9c9587c6ce607bf56c25b3d3d2de62056efe482dadc/seaborn-0.9.0-py3-none-any.whl (208kB)
    100% |████████████████████████████████| 215kB 682kB/s 
Collecting cairocffi (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/0f/0f/7e21b5ddd31b610e46a879c0d21e222dd0fef428c1fc86bbd2bd57fed8a7/cairocffi-1.0.2.tar.gz (68kB)
    100% |████████████████████████████████| 71kB 14.2MB/s 
Collecting matplotlib (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/ea/de/8c82ad7acc647357bc76d6a90385cba7df8e57d99e25ca38e5e12178682f/matplotlib-3.1.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (14.4MB)
    100% |████████████████████████████████| 14.4MB 1.1MB/s 
Collecting prompt_toolkit (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/f7/a7/9b1dd14ef45345f186ef69d175bdd2491c40ab1dfa4b2b3e4352df719ed7/prompt_toolkit-2.0.9-py3-none-any.whl (337kB)
    100% |████████████████████████████████| 337kB 1.2MB/s 
Collecting ptpython (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/01/16/5260314dbc2a03792e277e67578fee099ae1770db58d4f7fdda03225aef9/ptpython-2.0.4-py3-none-any.whl (47kB)
    100% |████████████████████████████████| 51kB 31.7MB/s 
Collecting docopt (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting Pygments (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/5c/73/1dfa428150e3ccb0fa3e68db406e5be48698f2a979ccbcec795f28f44048/Pygments-2.4.2-py2.py3-none-any.whl (883kB)
    100% |████████████████████████████████| 890kB 951kB/s 
Collecting typing (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/28/b8/a1d6b7cf322f91305bcb5e7d8f6c3028954d1e3e716cddc1cdce2ac63247/typing-3.7.4-py3-none-any.whl
Collecting glob2 (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/d7/a5/bbbc3b74a94fbdbd7915e7ad030f16539bfdc1362f7e9003b594f0537950/glob2-0.7.tar.gz
Collecting globster (from temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/4e/6e/d752c535e8e6b564f1228ad7add8ab7375f45dba6efb505d6123af1c7c75/globster-0.1.0.tar.gz
Collecting logutils (from rainbow_logging_handler->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/49/b2/b57450889bf73da26027f8b995fd5fbfab258ec24ef967e4c1892f7cb121/logutils-0.3.5.tar.gz
Collecting colorama (from rainbow_logging_handler->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting odfpy (from tablib->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/85/7d/8f6d1f2a4683be362b101c00232b4c3839e4e4a90e0945d8d43ec6aa671d/odfpy-1.4.0.tar.gz (715kB)
    100% |████████████████████████████████| 716kB 887kB/s 
Collecting backports.csv (from tablib->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/8e/26/a6bd68f13e0f38fbb643d6e497fc3462be83a0b6c4d43425c78bb51a7291/backports.csv-1.0.7-py2.py3-none-any.whl
Collecting openpyxl>=2.4.0 (from tablib->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/ba/06/b899c8867518df19e242d8cbc82d4ba210f5ffbeebb7704c695e687ab59c/openpyxl-2.6.2.tar.gz (173kB)
    100% |████████████████████████████████| 174kB 1.2MB/s 
Collecting xlrd (from tablib->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/b0/16/63576a1a001752e34bf8ea62e367997530dc553b689356b9879339cf45a4/xlrd-1.2.0-py2.py3-none-any.whl (103kB)
    100% |████████████████████████████████| 112kB 34.6MB/s 
Collecting xlwt (from tablib->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/44/48/def306413b25c3d01753603b1a222a011b8621aed27cd7f89cbc27e6b0f4/xlwt-1.3.0-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 2.2MB/s 
Collecting scipy>=0.14.0 (from seaborn->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/04/66/ec5f1283d6a290a9153881a896837487338c44639c1305cc59e1c7b69cc9/scipy-1.3.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (27.7MB)
    100% |████████████████████████████████| 27.7MB 493kB/s 
Collecting pandas>=0.15.2 (from seaborn->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/fc/43/fd867e3347559845c8f993059d410c50a1e18709f1c4d4b3b47323a06a37/pandas-0.24.2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (15.9MB)
    100% |████████████████████████████████| 15.9MB 984kB/s 
Collecting numpy>=1.9.3 (from seaborn->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/6b/be/608b7f72b851472388eafc010a5d46dae5d41610d0ac5df4c98c2ed1b865/numpy-1.16.4-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.9MB)
    100% |████████████████████████████████| 13.9MB 1.3MB/s 
Collecting cffi>=1.1.0 (from cairocffi->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/f0/48/5aa4ea664eba26dd5142558d04762f5065c02220b4665b3f7eecb9bb614e/cffi-1.12.3-cp37-cp37m-macosx_10_9_x86_64.whl (169kB)
    100% |████████████████████████████████| 174kB 1.7MB/s 
Requirement already satisfied: setuptools>=39.2.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from cairocffi->temci==0.7.13) (40.8.0)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e25769976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl (62kB)
    100% |████████████████████████████████| 71kB 34.8MB/s 
Collecting python-dateutil>=2.1 (from matplotlib->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
    100% |████████████████████████████████| 235kB 1.7MB/s 
Collecting kiwisolver>=1.0.1 (from matplotlib->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/df/93/8bc9b52a8846be2b9572aa0a7c881930939b06e4abe1162da6a0430b794f/kiwisolver-1.1.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (113kB)
    100% |████████████████████████████████| 122kB 1.9MB/s 
Collecting cycler>=0.10 (from matplotlib->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting six>=1.9.0 (from prompt_toolkit->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting jedi>=0.9.0 (from ptpython->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/68/42/6309f3871b2f8361764ac5b2fe6719f9c6e6561d9307d8cecda319cf5843/jedi-0.14.0-py2.py3-none-any.whl (1.0MB)
    100% |████████████████████████████████| 1.0MB 767kB/s 
Collecting defusedxml (from odfpy->tablib->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/06/74/9b387472866358ebc08732de3da6dc48e44b0aacd2ddaa5cb85ab7e986a2/defusedxml-0.6.0-py2.py3-none-any.whl
Collecting jdcal (from openpyxl>=2.4.0->tablib->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/f0/da/572cbc0bc582390480bbd7c4e93d14dc46079778ed915b505dc494b37c57/jdcal-1.4.1-py2.py3-none-any.whl
Collecting et_xmlfile (from openpyxl>=2.4.0->tablib->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/22/28/a99c42aea746e18382ad9fb36f64c1c1f04216f41797f2f0fa567da11388/et_xmlfile-1.0.1.tar.gz
Collecting pytz>=2011k (from pandas>=0.15.2->seaborn->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 1.4MB/s 
Collecting pycparser (from cffi>=1.1.0->cairocffi->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |████████████████████████████████| 163kB 2.8MB/s 
Collecting parso>=0.3.0 (from jedi>=0.9.0->ptpython->temci==0.7.13)
  Downloading https://files.pythonhosted.org/packages/68/59/482f5a00fe3da7f0aaeedf61c2a25c445b68c9124437195f6e8b2beddbc0/parso-0.5.0-py2.py3-none-any.whl (94kB)
    100% |████████████████████████████████| 102kB 30.6MB/s 
Installing collected packages: click, humanfriendly, pytimeparse, fn, cpuset-py3, wcwidth, logutils, colorama, rainbow-logging-handler, defusedxml, odfpy, backports.csv, jdcal, et-xmlfile, openpyxl, xlrd, pyyaml, xlwt, tablib, numpy, scipy, pyparsing, six, python-dateutil, kiwisolver, cycler, matplotlib, pytz, pandas, seaborn, pycparser, cffi, cairocffi, prompt-toolkit, Pygments, docopt, parso, jedi, ptpython, typing, glob2, globster, temci
  Running setup.py install for click ... done
  Running setup.py install for fn ... done
  Running setup.py install for logutils ... done
  Running setup.py install for rainbow-logging-handler ... done
  Running setup.py install for odfpy ... done
  Running setup.py install for et-xmlfile ... done
  Running setup.py install for openpyxl ... done
  Running setup.py install for pyyaml ... done
  Running setup.py install for pycparser ... done
  Running setup.py install for cairocffi ... done
  Running setup.py install for docopt ... done
  Running setup.py install for glob2 ... done
  Running setup.py install for globster ... done
  Running setup.py install for temci ... done
Successfully installed Pygments-2.4.2 backports.csv-1.0.7 cairocffi-1.0.2 cffi-1.12.3 click-8.0.dev0 colorama-0.4.1 cpuset-py3-1.0 cycler-0.10.0 defusedxml-0.6.0 docopt-0.6.2 et-xmlfile-1.0.1 fn-0.4.3 glob2-0.7 globster-0.1.0 humanfriendly-4.18 jdcal-1.4.1 jedi-0.14.0 kiwisolver-1.1.0 logutils-0.3.5 matplotlib-3.1.0 numpy-1.16.4 odfpy-1.4.0 openpyxl-2.6.2 pandas-0.24.2 parso-0.5.0 prompt-toolkit-2.0.9 ptpython-2.0.4 pycparser-2.19 pyparsing-2.4.0 python-dateutil-2.8.0 pytimeparse-1.1.8 pytz-2019.1 pyyaml-5.1.1 rainbow-logging-handler-2.2.2 scipy-1.3.0 seaborn-0.9.0 six-1.12.0 tablib-0.13.0 temci-0.7.13 typing-3.7.4 wcwidth-0.1.7 xlrd-1.2.0 xlwt-1.3.0
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by leodemoura** [comment]
However, `temci` doesn't see to be available :( 
The following command fails
```
temci exec --config speedcenter.yaml --out base.yaml
```
~/projects/lean4/tests/bench (master)$ temci
bash: temci: command not found
```

**Comment by Kha** [comment]
I see Python packaging is as simple as ever :) . On Linux the executable is placed at `/usr/local/bin/temci`. I *think* it should be the same for macOS, do you have that file, and the directory in your PATH?
Alternatively, try
```
$ pip3 show -f temci
...
Location: /usr/local/lib/python3.7/dist-packages
Files:
  ../../../bin/temci
...
```

**Comment by leodemoura** [comment]
Thanks. I used the `pip3 show` and found it at
```
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/../../../bin/
```

**Comment by leodemoura** [comment]
I merged the changes. It seems to be working, but it breaks on my Mac because I don't have gnu `time`. I will install it.

**Pull request closed without merging**
