### PR TITLE
chore: test results as job summary

### PR DESCRIPTION
**Pull request by Kha**
Tired of scrolling through and parsing the test output myself

### CODE REVIEW

**Comment by nomeata** [comment]
This will only help with `full-ci`, I guess, unless we find a way to extract that file from a (failed) nix build.

**Comment by Kha** [comment]
@nomeata It does now list the failing tests but actually showing the stdout output would require some ctest-specific changes to the action

image

**Comment by nomeata** [comment]
Well, it is an improvement, so merge and maybe iterate there?

We could additionally configure ctest to not print successful tests in the build log. Advantage: Errors are easier to find. Downside: no progress indication when looking at live logs.

**Comment by Kha** [comment]
> Well, it is an improvement, so merge and maybe iterate there?

Agreed

> We could additionally configure ctest to not print successful tests in the build log. Advantage: Errors are easier to find. Downside: no progress indication when looking at live logs.

Too bad `--progress` doesn't seem to work in Actions

**Pull request merged**
