### PR TITLE
feat: abbrev produces theorems where appropriate

### PR DESCRIPTION
**Pull request by kim-em**
This PR modifies the `abbrev` keyword, ensuring that it produces a `theorem` when the declaration is a `Prop`. This is convenient for the frequent current use case of `abbrev` to set up deprecations.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Is there any advantage of using `abbrev` over `theorem` in this case?

**Comment by kim-em** [comment]
> Is there any advantage of using `abbrev` over `theorem` in this case?

Yes, we can use `abbrev X := @Y`, to avoid having the type out the signature, when deprecating. In Batteries and below, we have `alias`, but I don't think `alias` is ready to move upstream (precisely because it results in us having too many ways to do the same thing: eventually I would like a unification of `abbrev` and `alias` functionality into a single keyword).

**Comment by kim-em** [comment]
I'm adding the `awaiting-review` tag as I would like another set of eyes on this before merging. It feels a bit hacky to me still. :-(

**Comment by nomeata** [comment]
For just offering something under a different name, I guess that can be done on the level of renaming variables.
```
theorem foo : True := .intro

open _root_ renaming foo → alias
```

Unfortunately deprecation attributes are attached to the underlying constant, not to the alias:

```
theorem foo : True := .intro

open _root_ renaming foo → alias

attribute [deprecated "test"] alias

/-- warning: `foo` has been deprecated: test -/
#guard_msgs in def ok := foo
/-- warning: `foo` has been deprecated: test -/
#guard_msgs in def not_ok := alias
```

If the latter could change then the whole use-case of providing alternative names could be moved from the level of definitions to the level of name resolution, which is likely more robust anyways?

**Comment by Kha** [comment]
@kim-em Could you explain what the limitations of the current behavior are, i.e. `abbrev` not creating a theorem?

Note that declarations changing their kind post-hoc can also be an issue for parallelism.

**Comment by kim-em** [comment]
> @kim-em Could you explain what the limitations of the current behavior are, i.e. `abbrev` not creating a theorem?
> 
> Note that declarations changing their kind post-hoc can also be an issue for parallelism.

It's not super important, but I have been [trying](https://github.com/leanprover-community/batteries/blob/lint_lean/BatteriesTest/lint_lean.lean) to the Batteries environment linter suite running on Lean itself, and all the abbrevs currently make the `defLemma` linter very noisy, and hard to be sure we're otherwise satisfying.

**Comment by Kha** [comment]
Ok, given the additional complication with parallelism, I'd prefer adjusting the linter instead

**Pull request closed without merging**
