### PR TITLE
feat: `if _ : cond then t else e` syntax

### PR DESCRIPTION
**Pull request by digama0**
This allows you to use `_` as the binder inside `dite` notation. This differs from `if cond then ...`  in that it desugars to `dite` instead of `ite`, and so in the body of the if statement you can make use of the hypothesis without naming it. This is useful when the `unusedVariables` linter wants to make the variable anonymous but it is important for the expression to be a `dite`.

### CODE REVIEW

**Comment by leodemoura** [comment]
I have hit the problem this PR is solving in the past (e.g., `h : c` is needed to discharge the condition at `a[i]` automatically). @Kha and I briefly discussed the possibility of elaborating all `if-then-else` using `dite`, and having `simp` theorems to convert the non-dependent ones back into `ite`.

**Comment by digama0** [comment]
As long as `ite` and `dite` both exist, I think the most predictable desugaring just uses `if _ : cond` as `dite` and `if cond` as `ite`.
One way to make your version "just work" would be to have `if cond then t else e` elaborate `t` and `e` with the appropriate condition variables in scope, and then if they ended up being used then construct a `dite` term, else `ite`. I worry about cases where you have metavariables in there though and want to reason about the expression anyway.

For proving purposes I think we do want a way to create `ite` terms directly, for similar reasons as why we don't always want `match h : cond with` dependent match style. But the main reason I see to support `if _ : cond` independent of whether `if cond` is "clever" is syntactic uniformity. It's a binder, so it should allow `_`.

**Comment by leodemoura** [comment]
> One way to make your version "just work" would be to have if cond then t else e elaborate t and e with the appropriate condition variables in scope, and then if they ended up being used then construct a dite term, else ite. I worry about cases where you have metavariables in there though and want to reason about the expression anyway.

We considered this option. It is not reliable because metavariables. If `t` or `e` contain a metavariable, we don't really know whether we need the variable or not.

**Comment by leodemoura** [comment]
> For proving purposes I think we do want a way to create ite terms directly, for similar reasons as why we don't always want match h : cond with dependent match style.

Yes, I agree.

**Comment by leodemoura** [comment]
Could you please rebase? We have conflicts at stage0.

**Review by leodemoura — APPROVED** [review]

**Pull request merged**
