### PR TITLE
fix: validate atoms modulo leading and trailing whitespace

### LINKED ISSUE #6011: Validation of atoms should ignore whitespace
### Description

New atoms introduced by `syntax` and its derived commands are not allowed to begin with digits or single or double quotes, nor may their first two characters be a valid prefix of an escaped name. They may also not be empty.

We surround atoms with spaces to indicate pretty-printing, but the atom validation routine does not ignore these spaces.

### Context

This came up while documenting the specific rules for infix operators in the reference manual.

### Steps to Reproduce

1. Enter the following code: `infix:40 "9" => Nat.add`
2. Observe the error message `invalid atom`
3. Add a space: `infix:40 " 9" => Nat.add`
4. The error message disappears

**Expected behavior:**

The error messages should be identical. An invalid atom doesn't become valid because it should be printed with spaces.

**Actual behavior:**

The declaration is accepted.

### Versions

From `live.lean-lang.org`: `"4.15.0-nightly-2024-11-08"`

### Additional Information

[Link to code](https://live.lean-lang.org/#project=lean-nightly&codez=MQUwbghgNgBAMiCA7AdGEAnAzgSwPZIDKALhjkgOYBQVA9ALT1WYZ4YBcM5kUOAJjAjE8AWyqMmLNp27R+MLAE8kxCAA8YSPHxAwA1uQEByYphEB9AJzmj42lWAUArhAx9zIrBSxckVcgBmOGrsACwADDAARJZRMAC8AHwwAHJCKBB8fDSOLm4eXj7k/khBIRHRMLEJyWnEGVlUQA)

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

### PR DESCRIPTION
**Pull request by david-christiansen**
This PR improves the validation of new syntactic tokens. Previously, the validation code had inconsistencies: some atoms would be accepted only if they had a leading space as a pretty printer hint. Additionally, atoms with internal whitespace are no longer allowed.

Closes #6011

### CODE REVIEW

**Comment by david-christiansen** [comment]
The failing test defines this operator:
```lean
/-- `f '' s` denotes the image of `s : Set α` under the function `f : α → β`. -/
infixl:80 " '' " => image
```

Should this be allowed? I would think not, because deleting the leading space makes current versions of Lean reject it, and I would expect that pretty printing instructions were orthogonal to token rules. On that assumption, I'll update the test.

**Comment by david-christiansen** [comment]
This notation is also [used in Mathlib](https://github.com/leanprover-community/mathlib4/blob/682fb6e943f5985f9e7b3fc6681c3706fba888d8/Mathlib/Data/Set/Operations.lean#L114-L115).

**Comment by digama0** [comment]
> Should this be allowed? I would think not, because deleting the leading space makes current versions of Lean reject it, and I would expect that pretty printing instructions were orthogonal to token rules. On that assumption, I'll update the test.

Why wouldn't this be allowed?

**Comment by david-christiansen** [comment]
If it should be allowed, then shouldn't it be allowed whether or not the pretty-printer is instructed to insert whitespace before it?

Today, `"''"` is rejected as an atom, but `" '' "` is accepted. I think that either both or neither should be accepted here. Does that make sense?

**Comment by digama0** [comment]
I agree. They should both be accepted.

**Comment by digama0** [comment]
The exception for empty character literals was added in #1931 . I think we need a similar exception at `Lean.Elab.Term.toParserDescr.isValidAtom`.

**Comment by Kha** [comment]
> The exception for empty character literals was added in #1931 . I think we need a similar exception at `Lean.Elab.Term.toParserDescr.isValidAtom`.

agreed

**Comment by david-christiansen** [comment]
Great, `''` is now allowed with or without whitespace as of [b2a0735](https://github.com/leanprover/lean4/pull/6012/commits/b2a073500f354379def2fd1690f0de0abb9584d8).

While I'm at it, we presently allow atoms with internal spaces. Should we?

This works, and I'm not sure it should:
```
infix:70 " <I like apples, they are delicious> " => Nat.add
#eval 3 <I like apples, they are delicious> 4
```

**Comment by david-christiansen** [comment]
Just to see if it breaks Mathlib, I gave it a go

**Comment by david-christiansen** [comment]
It seems that `open private` is a single atom.

**Comment by david-christiansen** [comment]
https://github.com/leanprover-community/batteries/pull/1050 makes `batteries` build for me with this. I think we're OK.

**Comment by digama0** [comment]
While I think batteries#1050 is reasonable, I don't see a particular reason to ban tokens including whitespace?

**Comment by david-christiansen** [comment]
This was a balance of footgun vs flexibility. A consequence of the way `open private` was specified in Batteries was that `open  private` or `open /- Extracting the secret treasures! -/ private` was banned, which could be surprising. This is also an easy mistake to make - it seems to work well in most cases, and then suddenly there's weird error messages for a few downstream users.

If someone really needs precisely that level of flexiblity for their DSL, it's still possible to drop down and write the corresponding `ParserFn` and parser info. But if your DSL has token rules that are very different from Lean's, then you're probably better off working mostly at that level anyway (like I do in Verso).

**Comment by digama0** [comment]
> This was a balance of footgun vs flexibility. A consequence of the way `open private` was specified in Batteries was that `open private` or `open /- Extracting the secret treasures! -/ private` was banned, which could be surprising. This is also an easy mistake to make - it seems to work well in most cases, and then suddenly there's weird error messages for a few downstream users.

I agree on this, it's not the first time this mistake has been made and I don't think there are any commands in batteries or mathlib that would want to do this. But that's justification for a linter at best.

**Comment by kim-em** [comment]
@david-christiansen, I'm seeing
```
/-- `f ''ᵁ U` is notation for the image (as an open set) of `U` under an open immersion `f`. -/
scoped[AlgebraicGeometry] notation3:90 f:91 " ''ᵁ " U:90 => (Scheme.Hom.opensFunctor f).obj U
```
erroring with "invalid atom" now. Can we add some further flexibility to allow this?

**Comment by david-christiansen** [comment]
> I agree on this, it's not the first time this mistake has been made and I don't think there are any commands in batteries or mathlib that would want to do this. But that's justification for a warning at best.

If a real-world use case arises, then we can revisit this. Right now, it doesn't seem like a good use of development resources - "no internal whitespace" is easy to implement and solves the problem, while making it a warning would require more time and increase the complexity of the code overall.

**Comment by digama0** [comment]
I had a use case for this come up:
```
axiom SProp.ip : UInt64 → SProp
prefix:80 "RIP ↦ " => SProp.ip
```
from some separation logic project I'm working on. As I understand it this will not work in the next version of lean, and the `prefix` command does not allow adding multiple string literals in that position. Could we make the `prefix` command either split the input on whitespace (preserving formatting), or allow multiple string tokens in that position?

**Comment by david-christiansen** [comment]
I'm not totally convinced by this use case for spaces in the tokens. It's not that it doesn't seem like what's being asked for is useful, it's just that it seems to me that the usefulness really comes from new features rather than from undoing this new validation step.

Keeping the old behavior would have resulted in a keyword with a single space in it. `RIP ↦` would be valid syntax, while `RIP  ↦` or `RIP /- This does the thing! -/ ↦` would not. This is precisely the footgun to be avoided, and I don't think that it's a compelling case for whitespace characters in tokens.

It doesn't seem bonkers to allow multi-token operators, though I'd like to see why a notation doesn't do what you want here. I think it's OK if operators make easy things easy, but don't cover a wide range of syntax, and from what I can see, you'd get all the benefits of a two-token prefix operator from a `notation`. `RIP` would indeed be a keyword, of course, but this is another one of those balancing acts between flexibility and consistency that doesn't strike me as a huge problem, though I of course don't have a ton of insight into the specifics of your project. What am I missing?

**Comment by digama0** [comment]
> It's not that it doesn't seem like what's being asked for is useful, it's just that it seems to me that the usefulness really comes from new features rather than from undoing this new validation step.

No disagreement from me on this! I just wanted to give you a reasonable use case to center your thinking on this one.

**Pull request merged**
