### PR TITLE
fix: (rcases) handle synthetic placeholders in targets

### LINKED ISSUE #4331: rcases leaking subgoals out of have
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [X] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [X] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [X] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

Using `rcases` on a term containing a hole leads to subgoals leaking out of the current `have`.

### Context

This was [discussed on Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/rcases.20subgoals.20leaking.20out.20of.20have). I came across this while refactoring something in the sphere eversion project.

### Steps to Reproduce

My original minimization was:

```lean
example : True := by
  have : ∃ k, 5 = 2 + k := by
    -- Using apply with a hole create a new goal right here
    -- apply Nat.exists_eq_add_of_le (?_ : 2 ≤ 5)
    -- Using rcases teleports the new goal outside of the have block
    rcases Nat.exists_eq_add_of_le (?_ : 2 ≤ 5) with ⟨k, hk⟩
    exact ⟨k, hk⟩
  trivial -- This trivial solves 2 ≤ 5
  trivial -- this one takes care of True
```

Kyle came up with a variant where the hole is not directly inside `rcases` but in a `let`:

```lean
example : True := by
  have : ∃ k, 5 = 2 + k :=
    let h := Nat.exists_eq_add_of_le (?_ : 2 ≤ 5)
    by
      rcases h with ⟨k, hk⟩
      exact ⟨k, hk⟩
  trivial -- this one takes care of True
  trivial -- This trivial solves 2 ≤ 5
```

**Expected behavior:** [Clear and concise description of what you expect to happen]

The new subgoal should be inside the `have`.

**Actual behavior:** [Clear and concise description of what actually happens]

The new subgoal leaks outside the `have`.

### Versions

Found with 4.8.0, reproduced in 4.9.0-nightly-2024-06-02 on live.lean-lang.org.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

### PR DESCRIPTION
**Pull request by llllvvuu**
Calls `getMVarsNoDelayed` on the targets and adds them to the goals list.

Closes #4331

### CODE REVIEW

**Comment by llllvvuu** [comment]
awaiting-review

**Comment by llllvvuu** [comment]
wip

**Comment by llllvvuu** [comment]
It looks like there are places in mathlib that rely on the "leaking" behavior of #4331. I guess I should make a mathlib patch to go with this?

**Comment by semorrison** [comment]
@llllvvuu, I've merged your Mathlib PR into `lean-pr-testing-4422`. In general, it's easier to just push commits directly to such branches, rather than going through a PR process.

**Pull request closed without merging**
