### PR TITLE
feat: register/chain LSP handlers in non-builtin `initialize` blocks

### PR DESCRIPTION
**Pull request by tydeu**

### CODE REVIEW

**Comment by tydeu** [comment]
cc @gebner, @Vtec234

**Review by Vtec234 — APPROVED** [review]

**Comment by tydeu** [comment]
cc @leodemoura / @Kha

**Comment by Kha** [comment]
I believe we have quite a few `IORef`s that are not guarded by any such condition. AFAIK it is critical only for environment extensions.

**Comment by leodemoura** [comment]
> I believe we have quite a few `IORef`s that are not guarded by any such condition. AFAIK it is critical only for environment extensions.

If these `IO.Ref`s are being updated by multiple threads, we should investigate. 
The `IO.initializing` and `Lean.initializing` are great for ensuring we have only one thread running. It is a great solution for `IO.Ref`s that are updated only during initialization, and then are read-only for many threads.

**Pull request merged**
