### PR TITLE
chore: switch obvious cases of array "bang"`[]!` indexing to rely on hypothesis

### PR DESCRIPTION
**Pull request by TomasPuverle**
Update certain uses of `arr[i]!` to use the "provably correct" version `arr[i]`, in order to use "best practices".

Some motivation and discussion on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Lean.20compiler.2Felaborator.20development.20question/near/472934715)

### CODE REVIEW

**Comment by TomasPuverle** [comment]
The changes themselves are trivial and purely mechanistic, and I deliberately avoided changing places where multiple arrays were involved - my plan is to address this separately.

However, working through this I noticed a few "paper cuts", which I posted about on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Indexing.20hypothesis.20observations/near/473969520)

**Comment by TomasPuverle** [comment]
I am happy to switch to any naming preference but there didn't seem to be a consistent convention that I could see.  Existing code typically used `h`, so I stuck with it.

**Comment by nomeata** [comment]
I think it has been tried, and caused problems with large definitions, and maybe also with tactics like `case` that revert some hypotheses picking it up when it shouldn't. I wouldn't rule it out, but I don't thinks is an easy route.

**Comment by TomasPuverle** [comment]
I had the same thought!  Just like with implicit arguments, I think it would be interesting to be able to introduce "implicit return values", e.g.

```
def foo (...) : Int { h: <some value> }
```

**Comment by TomasPuverle** [comment]
> I think it has been tried, and caused problems with large definitions, and maybe also with tactics like `case` that revert some hypotheses picking it up when it shouldn't. I wouldn't rule it out, but I don't thinks is an easy route.

Interesting!

**Pull request merged**
